### ISSUE TITLE
Hello, thx for your installer, i am installed and i am in ecstasy. I have a question, how switch between two monitor and focused on one monitor?

### ISSUE THREAD

**Issue by aquamaryne** [gh0stzk/dotfiles#105]

**Comment by gh0stzk** [comment]
Hello, unfortunately, the rices were made with only one monitor, it is a function that I can add but, since I do not have two or more monitors, I do not like to add functions that I have not tested.

But other people have already done it, I leave you a link on how you can achieve it.

https://github.com/gh0stzk/dotfiles/issues/8
