### ISSUE TITLE
Possible to ignore polybar on my second monitor?

### ISSUE THREAD

**Issue by Jayy001** [gh0stzk/dotfiles#11]
![image](https://user-images.githubusercontent.com/56607897/200172203-9fe72a7b-d985-46e1-82f9-f2f2d4ddf84c.png)
Is it possible for the window on my second monitor to ignore the "invisible" polybar?

**Comment by gh0stzk** [comment]
Hello, that happends because botom-pading is configured to "60" in bspwm config to make space for the bar, this setup were maked to make 1 monitor, because i have 1 monitor, its possible, yes, but u need to make some changes.

these links could help you to configure dual monitor for bspwm https://github.com/gh0stzk/dotfiles/issues/8
