### ISSUE TITLE
System Tray of the z0mbi3's EWW polybar is acting weird & Music control of Pamela's EWW polybar not here

### ISSUE THREAD

**Issue by AzhamProdLive** [gh0stzk/dotfiles#119]
Hey, it is I, with another issue, this time with the EWW polybars.

1rst issue : When using the z0mbi3 rice, and having more than 2 apps in the system tray, the apps are almost dipping out of the polybar and the screen (cf; screenshot n°1) 
2nd issue : When playing music with Spotify, and using the pamela rice, the music control from the EWW polybar straight up disapeared (cf; screenshot n°2)

N°1 ![image](https://github.com/gh0stzk/dotfiles/assets/73955243/46edd26e-c3f0-42db-807f-d9aa60fe422f)
N°2 ![image](https://github.com/gh0stzk/dotfiles/assets/73955243/f01e227b-ca2d-45c6-a53f-2cfe4ad9fd99)

Is there a possible fix to these issues ? or is it something wrong with my install possibly ?

**Comment by gh0stzk** [comment]
Just the other day when I updated that widget in pamela, I noticed that if you don't have the mpd module active, the song title doesn't appear obviously, and you can't click to open that widget, its not an error is the way it works, because the mpd module for polybar doesnt work with mpris player like spotify. Possibly i will change that module, or for a custom module....  i dont know but. I'm going to add a button to open the widget, possible today.
![Screenshot-02_09_2023-08-45-09](https://github.com/gh0stzk/dotfiles/assets/67278339/75886b63-3b26-4923-bed6-3b5f04cb5458)

The other thing, in my last commit I fixed the specific error in that widget in pamela, https://github.com/gh0stzk/dotfiles/commit/9fb628565879f983586e29e3c138512965e499f9

Just add these two lines at the top in .../bspwm/rices/pamela/widgets/eww.yuck
```
(defpoll time0 :interval "10s"  "date '+%H':%M")
(defpoll date :interval "10s"  "date '+%b %d'")
```

About polybar in z0mbi3, As you can see, there is not enough space due to the location of the systemtray, up there it looks cool but there is no space

That bar is made with eww, and eww at the moment I write doesn't have support for a systemtray, so I had to do a little trick and use polybar, but the polybar systemtray system is very bad, but apparently they are already working on making that the systemtray works like a module.

But for now, I'm sorry to tell you that it's not acting weird, it's just that the space there is insufficient, polybar only works in vertical position. But you can change location of the systemtray if you want, in the file ~/.config/bspwm/rices/z0mbi3/bar/polybar_tray.ini

**Comment by AzhamProdLive** [comment]
> About polybar in z0mbi3, As you can see, there is not enough space due to the location of the systemtray, up there it looks cool but there is no space
> 
> That bar is made with eww, and eww at the moment I write doesn't have support for a systemtray, so I had to do a little trick and use polybar, but the polybar systemtray system is very bad, but apparently they are already working on making that the systemtray works like a module.
> 
> But for now, I'm sorry to tell you that it's not acting weird, it's just that the space there is insufficient, polybar only works in vertical position. But you can change location of the systemtray if you want, in the file ~/.config/bspwm/rices/z0mbi3/bar/polybar_tray.ini

Oh okay, I see I see, thanks for the info :+1: 

Also I'm gonna try what you just sent me for pamela rice

**Comment by AzhamProdLive** [comment]
Oh, I already added those line to the eww.yuck of pamela, so this wasn't the issue :thinking:

**Comment by AzhamProdLive** [comment]
Also, currently getting an error when trying to start the mpd module 

![image](https://github.com/gh0stzk/dotfiles/assets/73955243/849d9a40-e8f0-4ff3-abd2-3a51e5e7d631)

**Comment by AzhamProdLive** [comment]
Aight, after a reboot the service runs, but still nothing on the eww bar 
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/4cc4c402-4aaa-423d-aa42-ef068e205b02)

**Comment by gh0stzk** [comment]
First, before my dotfiles, did you have mpd installed? If the answer is yes, how do you start the service? According to the wiki and how my installer activates it, it is at the user level `systemctl --user enable mpd.service` not with `sudo systemctl enable mpd.service` chack that first. 

then if you have all files configured like my wiki https://github.com/gh0stzk/dotfiles/wiki/Firsts-steps-after-installing#the-album-covers-in-notifications-and-widgets you need to playa song to make module appears, just open ncmpccp with `shift + alt + k`  and play something.

In the case nothing appears in ncmpccp, that player is tricky, you need to have at least one mp3 file in the directory configured, press in ncmpcpp the key "u" that will update the database.

**Comment by gh0stzk** [comment]
i see an error in your screenshot failed to open /var/lib/mpd/mpdstate so thats maybe because mpd is enabled at system level not user level, the mpdstate in my config is in  ~/.config/mpd/

**Comment by gh0stzk** [comment]
if your mpd daemon is enabled system level change it and reboot then try again

**Comment by gh0stzk** [comment]
about eww widget in pamela, open a terminal and check if works fine the widget with this command `~/.config/bspwm/rices/${RICETHEME}/widgets/WidgetLaunchers --musicplayer`

**Comment by AzhamProdLive** [comment]
The widget works fine, and I can control my spotify music from it, but still nothing in the eww bar 
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/908a9433-3b8d-4fb1-849a-22ce7652b34d)

**Comment by gh0stzk** [comment]
![Screenshot-02_09_2023-09-22-03](https://github.com/gh0stzk/dotfiles/assets/67278339/ce80c6ff-0c3a-4cc6-99cc-7a459ad2cc52)

I add this for now to mpd module to make it clickeable and can open widget, i will push the commit in 2 ahours, now in mexico are 9:48am and i will go to somewhere to brakfast.

**Comment by AzhamProdLive** [comment]
Aight, i'll try that on my end and tell you how it goes

**Comment by gh0stzk** [comment]
> Aight, i'll try that on my end and tell you how it goes

In the image you can see the format-offline part, that's what I added, if you want to add it before. But I won't leave it like that, I will add an icon independent of the mpd module, so that even if you don't even have mpd installed, the icon will be displayed and you can open the widget and control spotify or others.

**Comment by AzhamProdLive** [comment]
> In the image you can see the format-offline part, that's what I added, if you want to add it before. But I won't leave it like that, I will add an icon independent of the mpd module, so that even if you don't even have mpd installed, the icon will be displayed and you can open the widget and control spotify or others.

Noted noted, i'll mostly use it as a placeholder fix, while waiting for your commit in here :+1:

**Comment by AzhamProdLive** [comment]
Small update : 
Trying to play **local** music with mpc triggers the mediacontrol out, but as soon as I clear the queue, the mediacontrol dissapear, and also, I just added the line for format-offline part, and kinda didn't fixed the issue, so i'll wait for the commit to pop in

N°1 ![image](https://github.com/gh0stzk/dotfiles/assets/73955243/df3e2ec5-f9ba-4492-ba16-4af8b422e944)
N°2 ![image](https://github.com/gh0stzk/dotfiles/assets/73955243/3804075d-0f98-4f60-a054-4977e92670b1)

**Comment by gh0stzk** [comment]
Yes, do a `mpc clear` cleans your playback queue, cleans all the info in mpd and that's why the module disappears, it's not really a bug, that module works like that, maybe it would be good to open an issue on the polybar github so that this behavior is modified.

**Comment by AzhamProdLive** [comment]
Weird stuff is that if I use the cristina rice, the button stays here, so I don't really know what's causing it
And if it's supposed to work like that, I guess I don't really have to make an issue over the Polybar's github

![image](https://github.com/gh0stzk/dotfiles/assets/73955243/8ff06bfd-24b6-43e4-9933-a723d6dd520d)

**Comment by gh0stzk** [comment]
Maybe you are misunderstanding how it works, in Cristina, the icon does not disappear whether or not the mpd is active, because that icon in Cristina's rice is not a module that depends on mpd. In Pamela's rice, the way my configuration is, there is no icon, instead of an icon, I made the title of the song clickable, but that title only came from a source like ncmpccp being played. If mpd is not active for whatever reason, it will not show a title, therefore, that title will not be clickable and even if you have spotify open, the title will not be shown.

That was my mistake, many people simply uninstall mpd or don't use it, therefore that module will always be empty and there will never be a title to click on and open the widget.

But I already added the change, I'll leave it to you in the next message.

**Comment by AzhamProdLive** [comment]
Oh, yea I indeed misunderstood how it was supposed to work, thanks for the clarification, and yea, I indeed first uninstalled mpd because I use Spotify, which explains why I'm not fully aware of that, thanks for the clarification though

> But I already added the change, I'll leave it to you in the next message.

Thanks, appreciate

**Comment by gh0stzk** [comment]
then open modules.ini in pamela rice and add this module wherever you want

```
[module/mplayer]
type = custom/text
content = ""
content-foreground = ${pamela.green}

click-left = ~/.config/bspwm/rices/${RICETHEME}/widgets/WidgetLaunchers --musicplayer
click-right = OpenApps --music
```
Then open config.ini and add in line 321 mplayer, must look like my image, restart bspwm `super + alt + r ` and its done.

![Screenshot-02_09_2023-03-23-49](https://github.com/gh0stzk/dotfiles/assets/67278339/16242ed9-b401-4cc6-8fdb-19be23b369f1)

I put it at the right of updates icon, but you can place it wherever you want.

mpd module only works with mpd, spotify or other mpris player not work with mpd, im planning to trash it, and replace it with a good spotify module, but meanwhile, this.

**Comment by gh0stzk** [comment]
![Screenshot-02_09_2023-03-27-44](https://github.com/gh0stzk/dotfiles/assets/67278339/00d76a85-4e69-41df-b4f3-9afdd0909c40)

**Comment by AzhamProdLive** [comment]
Aight, just did all that and I might be stupid but it straight still doesn't work ? No ideas why now, which is even weirder. 
I do have music playing, but the widget doesn't show anything 

![image](https://github.com/gh0stzk/dotfiles/assets/73955243/d55fb530-b066-46cb-9472-fd5c36e03107)

**Comment by AzhamProdLive** [comment]
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/dc2d7a4b-9905-47c0-8d3c-ed6ca6a7c6f2)

**Comment by AzhamProdLive** [comment]
Gonna just send the things I modified here to see if I did smth wrong or not
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/43e8bddb-aad7-400e-999b-34e3bab5da86)

![image](https://github.com/gh0stzk/dotfiles/assets/73955243/55530a24-af2b-45f9-81b0-9eaacff37d17)

**Comment by AzhamProdLive** [comment]
I'm gonna try to reinstall the eww files from the repo and redo the changes to see if it comes from the module or my comp

**Comment by AzhamProdLive** [comment]
Aight, after redownloading and rebooting, it doesn't seems to come from here, so I guess I'll try something else rq

**Comment by AzhamProdLive** [comment]
aight, tried to see if it was because of the mpd service change we did some hours ago but still doesn't seems to be that, so I don't really know now, I'm gonna try this in a VM and see what did I do wrong

**Comment by AzhamProdLive** [comment]
Aight, just tried in a VM, and it works, so uh yea

**Comment by AzhamProdLive** [comment]
If I reinstall the rices with your script, will it override all the already existing settings or not at all ? So I know if I can reinstall the things I need or nah

**Comment by AzhamProdLive** [comment]
NVM I FINALLY FIXED IT LMAO

I don't know how but, copy pasting all the scripts from your script folder on the github fixed it, so it might've been an edit I did on my end, closing this with comment and thanks for the help over this !

**Comment by gh0stzk** [comment]
> NVM I FINALLY FIXED IT LMAO
> 
> I don't know how but, copy pasting all the scripts from your script folder on the github fixed it, so it might've been an edit I did on my end, closing this with comment and thanks for the help over this !

Ah... maybe the MediaControl in ..bspwm/scripts/ i updated 3 days ago, a big update.. maybe thats the reason...

**Comment by AzhamProdLive** [comment]
> Ah... maybe the MediaControl in ..bspwm/scripts/ i updated 3 days ago, a big update.. maybe thats the reason... 

Maybe maybe, I had the updated thing tho, but maybe copy-pasting the file helped to fix 🤔

Oh well, now it's done and working, so I can get some sleep, because it's 1 am other there ahah
