### ISSUE TITLE
error or bug?

### ISSUE THREAD

**Issue by oxzh** [gh0stzk/dotfiles#143]
Hi👋 i tried to install your dotfiles in fresh install, minimal, using the short url,
"curl -L https://is.gd/gh0stzk_dotfiles -o $HOME/RiceInstaller" following the steps, on last step to run the file, ./RiceInstaller, said he has a error in line one, and pointer to a link, i dind't remember what, but see if really has an error! on line one

**Comment by gh0stzk** [comment]
Hard to say, i read your issue post and i double check the command and url, and the script is succesfully downloaded. That error is because the script was not downloaded correctly. Maybe you were unlucky enough to download the script when the server was down or something... Try directly with the large url.

**Comment by oxzh** [comment]
yeyeye, i was already installed the rice, i just warning u, thx for rice🤝
