### ISSUE TITLE
Resolution fix

### ISSUE THREAD

**Issue by HinaHyugaHime** [gh0stzk/dotfiles#152]
can you tell me how to make it completely compatable with 1920x1080p also the first 2 ls commands for system.ini for after gives me blanks and if I go to the directory its empty

**Comment by HinaHyugaHime** [comment]
and I am running a desktop incase that makes any difference in the system.ini

**Comment by gh0stzk** [comment]
Hello, yes if you are in a desktop is normal that the 2 first ls command gives u a blanks, because your system doesnt have a battery. In this case, only remove the battery and brightness modules from the file ~/.config/bspwm/rices/RICE NAME/config.ini

![Screenshot-09_12_2023-09-28-29](https://github.com/gh0stzk/dotfiles/assets/67278339/400534df-f195-4d80-b179-1a36d1abe2eb)

Look for battery and brightness and remove it from the left, center, or right modules. You must do that in all rices config.ini file.

Regarding your resolution, polybar and other components of the themes, I make sure that they use percentages, so that they adapt to the different resolutions, however, if there are parts that require manual intervention, such as some aspects of the eww widgets, but it would be It's easier if you tell me which part doesn't look the way you would like and then it would be easier to help you.

**Comment by HinaHyugaHime** [comment]
Im meaning the system.ini in the post install it was /.config/bspwm/scripts/system.ini https://github.com/gh0stzk/dotfiles/wiki/Firsts-steps-after-installing

**Comment by gh0stzk** [comment]
oh ok, yes is the same, if you dont have a laptop, then you dont have an adapter and a battery, it doesnt matter if the are blanks in that file. if your network is incorrect just do a `ip a` look for your interface and edit system.ini manually. The sys_graphic_ccard var in that file is also for laptos, if is blank is fine.

**Comment by gh0stzk** [comment]
i use a desktop too and my file is like this

![Screenshot-09_12_2023-09-46-54](https://github.com/gh0stzk/dotfiles/assets/67278339/c27ecd2e-91fe-4dc9-8bba-9cf5ec9ef110)

**Comment by HinaHyugaHime** [comment]
Okay, thank you, I wasnt sure if some buttons didnt work because resolution or if it was what but are most taskbar stuff not clickable?

**Comment by gh0stzk** [comment]
Unfortunately, polybar or other bars in the wms, many modules are only informative, but you can modify them to launch an application, for example, make the network icon when you click it launch networkmanager or other, etc.

**Comment by HinaHyugaHime** [comment]
Im fairly new to ricing so do you mind explaining how I could do that?

**Comment by HinaHyugaHime** [comment]
also appreciate how supportive you are especially vs other people

**Comment by gh0stzk** [comment]
Yes take a example for other module in emilia, like "date module" open modules.ini in emilia rice, look for date module, is almost at top.

`label = "%{A1:OpenApps --calendar:}%time%%{A}"`

the trick is formatting the output `%{A1:SOMEAPP:}%time%%{A}"`


**%{A1:SOMEAPP:}** somepolybarlabel **%{A}**

thats how you make clickleable a module, just change someapp for the app you want.

reference https://github.com/polybar/polybar/wiki/Formatting#action-a

**Comment by HinaHyugaHime** [comment]
how do I get it to stay on one wallpaper?

**Comment by gh0stzk** [comment]
> how do I get it to stay on one wallpaper?

https://github.com/gh0stzk/dotfiles/wiki/Set-your-own-wallpaper
