### ISSUE TITLE
Non issue - Polybar

### ISSUE THREAD

**Issue by zebo1o1** [gh0stzk/dotfiles#156]
HI there
Was wondering how i can add a little transparency to polybar ?
Also , how to change location info for the weather module 
Amazing work by the way

**Comment by gh0stzk** [comment]
the easy way to add transparency to some polybar is with picom, but because there are another 11 themes, that will add transparency to all other polybars.So the way my config do it is using the native polybar transparency function, you need to:

- Open the file colors.ini located at ~/.config/bspwm/scripts/
- Search for the theme name you want to add transparency to polybar
- Edit the `bg = #color` adding the transparency level at the start of the color, which you can find in this page https://davidwalsh.name/hex-opacity

For example JAN rice uses 90% transparency, in the table of that page yo can see that 90% transparency corresponds to E6, so you need to add E6 to the hex color #**E6**212a4c

**Comment by zebo1o1** [comment]
Thank you so much
