### ISSUE TITLE
Cool error that decided to make Rofi not work, and so the rices 

### ISSUE THREAD

**Issue by AzhamProdLive** [gh0stzk/dotfiles#157]
Hello there, it is I, with an issue that is actually not really nice.

So I saw this new update that adds a Wallpaper selector, with some other nice updates like the monitor detection, but this is not why I'm here today.

After updating everything and restarting the WM, my bar just, disappeared, leaving me with no bar, so I decided to change the rice to refresh, because it would maybe fix it, but i'm greeted with these errors
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/33e2138c-d5d7-43af-883f-6d1e5ed10aa7)
 
The first error looks like a issue with the name of the path, but changing it to ```/home/azhmprd/.config/bspwm/rices``` gives me this error ```./RiceSelector: line 21: read: read error: 0: Is a directory```

Another error that might be linked, is that when I check the files with intellijIdea to see the type files, RiceSelector comes out unknown instead of the usual script file (see screenshot again)
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/1ccf3559-4e53-485e-8357-81508329f2f7)

For now I'm stuck with having no bar at all, which is really unfortunate, but I'm trying some fixes to see if it works, hoping there is a fix to my current issue

Do you have any ideas what could cause this problem ? Thanks in advance

**Comment by AzhamProdLive** [comment]
Okay nevermind, it seems that i was missing a dependency because I can't read lol, installing ```xorg-xdpyinfo``` fixed it.

Keeping the issue open in case of people facing the same issue xD

~~also that didn't seems to fix the issue of RiceSelector not showing as a Script in InteliJ, I need to search more on that~~

**Comment by AzhamProdLive** [comment]
Also, for the future people that will see this issue, if your WallSelector doesn't work, check in your terminal if you can run the script, if you get a message saying ```Permission denied```, you'll have to chmod the file to allow it to run, or change the permissions with Thunar ! 

Example : If you get the ```Permission denied``` error
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/68c4aae0-b9fb-4bb7-8760-68b84ed54409)
1- In the same terminal, type ```chmod +x WallSelect```
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/a15ed09f-9fbb-4a3e-8224-8a52bb9bb7af)
2- Try the command again, if it output no error, then jackpot, you fixed the issue !
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/d7c21c29-cbd8-4e65-b84e-7d75ab17599d)

If you are too scared to use the Terminal way, you can do the Thunar way 
1- Go in $HOME/.config/bspwm/scripts
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/8f597bee-ae7a-48ff-afbc-1506ae63eaa4)
2- Right click on WallSelect and go on properties, you should see this afterwards 
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/09b819e8-37c3-4eac-b168-2b80c4910aa4)
3- Go in "Permissions"
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/e7c377e2-b738-42d8-95f5-6761e5dbbd73)
4- Tick the "Allow this file to run as a program" box 
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/40c3303e-7b9a-4c10-ae15-e5a998ffa988)
5- Try the shortcut again (super + alt + w), now it should work !

**Comment by gh0stzk** [comment]
I think the problem is that you download the files, not clone the repo, if you download files, the permissions, the "execute permissions" dissapear. you need to clone the repo to preserve persmissions.

With that say, in the new wallselect, if you dont have the xdpyinfo or the convert package, a dunst notification shows you need to install xorg-xdpyinfo and imagemagick packages. But here the problem is you cant launch it because script doesnt have execute permissions. But i will add that notification to riceselector too.

I see your pull request but is not necessary, all the scripts are executables, but you need to clone the repo to preserve permissions. And not all files in scripts dir need to be executables, like .rasi ones for example.

**Comment by AzhamProdLive** [comment]
> I think the problem is that you download the files, not clone the repo, if you download files, the permissions, the "execute permissions" dissapear. you need to clone the repo to preserve persmissions.

Indeed that might be the issue, I noticed that when trying to clone the repo

> With that say, in the new wallselect, if you dont have the xdpyinfo or the convert package, a dunst notification shows you need to install xorg-xdpyinfo and imagemagick packages. But here the problem is you cant launch it because script doesnt have execute permissions. But i will add that notification to riceselector too.

Good idea, also, the imagemagick isn't mandatory (at least for me) I managed to make it work without it.

> I see your pull request but is not necessary, all the scripts are executables, but you need to clone the repo to preserve permissions. And not all files in scripts dir need to be executables, like .rasi ones for example.

That's fair 👍

**Comment by gh0stzk** [comment]
> Good idea, also, the imagemagick isn't mandatory (at least for me) I managed to make it work without it.

For RiceSelector is not neccesary because takes images from ...bspwm/rices/RICETHEME/preview.webp image

But for wallselect is mandatory it uses convert command which came from imagemagick, that will create new images in your ~/.cache dir from your wallpapers in the rice you are. I need to use convert command because first, load entire walls could be heavier, second all walls have different aspect ratios, resolutions, sizes, in rofi will be showed in different sizes and that breaks the look of that menu, so the script take the images from .../RICETHEME/walls/ dir, convert them to a unique size "500x500" and create new ones in .cache dir.
