### ISSUE TITLE
Eww don'n fade out in Fullscreen videos

### ISSUE THREAD

**Issue by carlosonrails** [gh0stzk/dotfiles#159]
Playing around with zombi3, it's showing this behavior when I do Super+f
![image](https://github.com/gh0stzk/dotfiles/assets/69637662/ce5608f1-81d3-4534-a0e6-73a324e844d7)

![image](https://github.com/gh0stzk/dotfiles/assets/69637662/d789af35-63fa-46ba-93b8-66deea2d00ef)

**Comment by gh0stzk** [comment]
Yes is an issue i need to fix and there are some fixes to deal with. The first one is this code in bspwmrc, is an example i**t will not work in my config ok**, because i need to adapt it to the rices with eww bar (z0mbi3, andrea) and for the widgets calendar, etc,

```bash
bspc subscribe node_state | while read -r _ _ _ _ state flag; do
    if [ "$state" != "fullscreen" ]; then
        continue
    fi
    if [ "$flag" == on ]; then
        $HOME/.local/bin/eww -c $HOME/.config/eww/bar close-all
  else
        $HOME/.local/bin/eww -c $HOME/.config/eww/bar open bar
    fi
done &
```
another fix that will work now is with the **Super + h** keybind. that hide bars in all themes and you unhide with **Super + u** works with polybar and eww.

**Comment by carlosonrails** [comment]
Thanks for the replay. I'm using Super+h. One more question. Where can I decrease this margin left of the bar?

**Comment by gh0stzk** [comment]
In the eww.yuck file located at ~/.config/bspwm/rices/z0mbi3/bar/   almost at the end of file you will se a geometry :x "15px" change that 15px for whatever you want.

**Comment by gh0stzk** [comment]
You can reduce the space of the bars in polybar from the confing.ini file inside each theme folder.

offset-y =

**Comment by carlosonrails** [comment]
yep. That was my misunderstanding. I was looking for the offset in zombi3. Really like vertical bar. It helps a lot with tiny laptops like mine.
