### ISSUE TITLE
Can you please make a minimal setup to run your dotfiles?

### ISSUE THREAD

**Issue by Pranav-Saraswat** [gh0stzk/dotfiles#163]
Please Try to make a minimal arch setup to install your dotfiles with the necessary and some cool packages to install it

**Comment by gh0stzk** [comment]
What do you mean by minimal installation? Arch installation?

The dotfile installer installs all the minimum required packages you need to use my dots.

But of course it is assumed that you already have an arch installation with xorg and your video driver configured. Because minimal installation there can be many setups, I can't get involved or decide which login manager you want to use, for example.

Here in another repo I have an arch installation script that I use on one of my older machines, it installs functional arch, it's a minimal installation, you might want to give it a read.

**Comment by Pranav-Saraswat** [comment]
Can you share me that repo?

**Comment by gh0stzk** [comment]
https://github.com/gh0stzk/Arch-Install/blob/main/me_z0mbi3.sh

It's that one but don't use it, if you wanted to use it, you would have to modify the grub part, change it to efi, among other things.

This is just an example of a minimal installation, if I remember correctly you end up with an installation with only 620 packages, uses lightdm as the login manager, and thre is no wifi setup because in that machine i dont use wifi only ethernet.
