### ISSUE TITLE
what is this for?

### ISSUE THREAD

**Issue by 0xN1nja** [gh0stzk/dotfiles#164]
on line 68 (OpenApps script)
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/6c1e149a-1f80-4129-8640-fb0a12c6414b)
what if I change geany to nvim?

**Comment by gh0stzk** [comment]
All applications that are opened or launched from polybar or eww call that file, which means that you only have to edit that file with your favorite applications so that they open in all themes. Otherwise you would have to edit each of the 12 themes with your favorite applications which is not convenient.

**Comment by 0xN1nja** [comment]
in jan rice, how can I increase the font size of the workspaces:
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/f81f9ca1-5c3c-4f38-a1d0-ebbc71ee008a)

**Comment by gh0stzk** [comment]
From what I see you edited the bspwm module of the jan theme, in this case you would have to edit the config.ini file in that directory

font-0 = "Inconsolata Semi Condensed Extra Bold:size=11;1"

edit that part, the current size is 11, change that value to the desired one.

**Comment by 0xN1nja** [comment]
also, could you please clarify the significance of value after semicolon?
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/8ae72fb4-3e44-4484-87a9-59671d588c09)

**Comment by gh0stzk** [comment]
It is the vertical position that source will have. All fonts vary in size and that value helps to center the font correctly.

**Comment by 0xN1nja** [comment]
alright thanks!
