### ISSUE TITLE
How can I resize the bar ?

### ISSUE THREAD

**Issue by endermeme** [gh0stzk/dotfiles#166]
Your config is really beautiful but it's too big for me, so I want you to show me how to adjust the size, by the way, I need the location of the config file and I use a 1280x768 laptop screen

**Comment by endermeme** [comment]
![IMG_20231218_184935](https://github.com/gh0stzk/dotfiles/assets/91008703/8359f274-5a80-44c9-8157-6f5c6bb54a2e)
It looks missing like this

**Comment by gh0stzk** [comment]
Hello, you need to edit the config.ini file located at ~/.config/bspwm/rices/emilia/

width = 90%
offset-x = 5%

These are the actual values for example if you want to increase the size to 95% you need to .

width = 95%
offset-x = 2.5%

the offset-x corresponds to the space on the sides of the bar, you need them to be symmetrical so if you enlarge the bar to 95% you have 5% free, so you give it 2.5 x-offset so that each space has the same space.
