### ISSUE TITLE
Ajuda com os temas rice

### ISSUE THREAD

**Issue by dbmb91** [gh0stzk/dotfiles#169]
Gh0stzk, bom dia.
Desde já, gostaria de parabenizá-lo pelo excelente trabalho com o seus Rices!
.
Caso não esteja ocupado... você pode me ajudar?
Eu realizei a instalação do seus doltfiles, mas não é todos o sistema que se ajusta as cores dos rice.
Exemplo: eu escolho um tema dark, mas tem algumas telas que ficam com o tema em branco. Tipo o thunar.
.
Tem algum ajuste que pode ser feito para todo o sistema ficar com as cores certas.
.
Peço desculpas pelo incomodo. E ainda estou aprendendo como funciona o mundo linux.
Obrigado.

**Comment by gh0stzk** [comment]
Olá, bom dia, utilizei o tradutor pois não entendo português, então espero que minha resposta seja bem compreendida e você consiga entender.

A dúvida que você tem é porque a única coisa que meus temas não mudam é o tema gtk.

Você tem que alterá-lo manualmente usando **lxappearance** `sudo pacman -S lxappearance ` baixe o tema gtk de sua escolha e coloque-o em ~/.themes e em lxappearance ele estará na lista.

No entanto, é uma funcionalidade que eu queria adicionar há muito tempo, mas não encontrei um tema gtk base que fosse leve, pois adicionar 12 temas gtk ao repositório aumentaria muito o tamanho do repositório. Mas essa funcionalidade pode ser facilmente implementada usando o aplicativo xsettingsd, mas até eu encontrar um tema leve e editá-lo para todos os 12 temas, não irei implementá-lo e dá muito trabalho, mas enquanto isso você tem que fazer isso manualmente com "lxappearance"

In english:

Hello, good morning, I used the translator because I don't understand Portuguese, so I hope my answer is well understood and you can understand.

The question you have is because the only thing that my themes don't change is the gtk theme.

You have to change it manually using **lxappearance** `sudo pacman -S lxappearance` download the gtk theme of your choice and put it in ~/.themes and in lxappearance it will be in the list.

However, it is a functionality that I have wanted to add for a long time, but I have not found a base gtk theme that is lightweight, since adding 12 gtk themes to the repository would greatly increase the size of the repository. But that functionality can be easily implemented using the xsettingsd application, but until I find a lightweight theme and edit it for all 12 themes, I won't implement it and it's a lot of work, but in the meantime you have to do it manually with "lxappearance"

**Comment by gh0stzk** [comment]
![imagen](https://github.com/gh0stzk/dotfiles/assets/67278339/99bd8f07-9f8b-442c-9497-3271d671d549)

lxappearance app.

**Comment by dbmb91** [comment]
Gh0stzk, good afternoon.
Thank you very much for your feedback.
.
I can understand, thanks!
.
I even installed lxappearance and managed to change a theme in some rice... but it didn't change in other rices. I thought I was wrong.
.
Now that I know there were no problems with the installation... I'm going to use lxappearance again.
In this case, can you guide me on how I add a theme to each rice?
Example: I want to use the theme: "Dracula" in Emilia's rice. and use the Theme: Light no Rice by Aline
So when I change the rice it changes the system theme too.
.
As in the example below.

https://plus.diolinux.com.br/t/script-instale-as-personalizacoes-e-temas-archcraft-em-diversas-distros/40325

.
.
Gh0stzk, boa tarde.
Muito obrigado pelo retorno.
.
Eu conseguir entender sim valeu!
.
Eu até instalei o lxappearance e conseguir mudar um tema de algum rice... mas como não mudava dos outros rices. achei que estava errado. 
.
Agora que eu sei que não houve nenhum problema com a instalação... vou usar o lxappearance novamente.
Nesse caso você pode me orientar em como eu adiciono um tema para cada rice?
Exemplo: quero usar o tema: "Dracula" no rice da Emilia. e usar o Tema:  Light no Rice da Aline
Para quando eu mudar o rice ele mudar o tema do sistema também.
.
Como no exemplo abaixo.

https://plus.diolinux.com.br/t/script-instale-as-personalizacoes-e-temas-archcraft-em-diversas-distros/40325

**Comment by dbmb91** [comment]
I'm also using translator!
Hum true.
As I don't have enough knowledge. I didn't install pure archlinux!
I'm using Manjaro xfce!
with yay enabled
.
.
Também estou usando tradutor!
Hum... verdade.
Como eu não tenho conhecimento suficiente. Eu não instalei o archlinux puro!
Eu estou usando o Manjaro xfce!
com o yay habilitado.

**Comment by gh0stzk** [comment]
Yes, if you configure a gtk theme with lxappearance that theme will be persistent in all 12 rices, because the gtk theme is configured globally regardless of the rice or wm that you use. You have to change it manually unfortunately.

Regarding the idea you want to do, it is exactly the functionality I want to add and it is a little more laborious, I will try to explain to you in general terms how it would be done.

It would be done exactly how archcraft does it.

First you install the xsettingsd application.

Then you have to add it to the bspwmrc file so that it is loaded every time you start bspwm

```bash
# Lauch xsettingsd daemon
xsettingsd --config="~/.config/bspwm/xsettingsd &
```

that xsettingsd file must contain this skeleton code:

```
Net/ThemeName "Arc-Dark"
Net/IconThemeName "Arc-Circle"
Gtk/CursorThemeName "Qogirr"
Net/EnableEventSounds "0"
Net/EnableInputFeedbackSounds "0"
Xft/DPI "-1"
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/Antialias 1
Xft/RGBA "none"
```

That is the base file that sets the gtk theme. Now how do you make it so that in my dotfiles, every time you change rice, the gtk theme automatically changes depending on the selected rice?

Well, it's easy but laborious. Inside each rice folder, there is a file called Theme.sh, this file is the one that controls the change of colors and other options for each rice, you need to add a function that is responsible for modifying the xsettingsd file every time you change the rice, this would be an example of the code, it may be good or it could be more efficient but as I say, it is only an example:

```bash
apply_appearance() {
	XFILE="~/.config/bspwm/xsettingsd"

	# apply gtk theme, icons, cursor & fonts
		sed -i -e "s|Net/ThemeName .*|Net/ThemeName \"DRACULA\"|g" ${XFILE}
		sed -i -e "s|Net/IconThemeName .*|Net/IconThemeName \"DRACULA\"|g" ${XFILE}
		sed -i -e "s|Gtk/CursorThemeName .*|Gtk/CursorThemeName \"CURSORTHEME\"|g" ${XFILE}
}
```
Then you add "apply_appearance" at the end of Theme.sh

So every time you change the theme, that code will overwrite the file in ~/.config/bspwm/xsettingsd with the new values ​​and the gtk theme will change automatically.

But you have to add that function in the 12 Theme.sh by modifying the name of the gtk theme that you must already have previously in the ~/.themes/ folder

Broadly speaking, this is how I would do it.

**Comment by dbmb91** [comment]
Gh0stzk, Thanks again for getting back to us.
I reinstalled your doltfiles here on the virtual machine.
I'll try to do what you suggested.
Thank you very much.
And sorry for the inconvenience.
Hug!
.
Gh0stzk, Obrigado novamente pelo retorno.
Eu instalei novamente seus doltfiles aqui na maquina virtual.
Vou tentar fazer o que você sugeriu.
Muito obrigado mesmo.
E desculpe o incomodo.
Abraço!

**Comment by gh0stzk** [comment]
Não há problema, se eu puder ajudá-lo, ficarei feliz em fazê-lo.
