### ISSUE TITLE
how can i update dotfiles?

### ISSUE THREAD

**Issue by Rainy-chan** [gh0stzk/dotfiles#18]
I would like to update the topic, because as I understand it, you are updating it.

**Comment by gh0stzk** [comment]
The easy way would be to clone my repository again and overwrite the new files with the old ones. But it's not practical since most people will made a lot of changes and overwriting the files with my updated ones will make them lose their edits.

Another less practical but safe solution would be to go to https://github.com/gh0stzk/dotfiles/commits/master, there the commit history is shown, where you can see what files I edited and what new or modified code there is.

But it won't be so much of a problem because there really isn't much to do with these rices anymore, I don't think I'll add anything else. the last thing i wanna do is a script to install the dotfiles.
