### ISSUE TITLE
Wifi doenst connect

### ISSUE THREAD

**Issue by airi5609** [gh0stzk/dotfiles#181]
I've been trying commands to connect to Wi-Fi for more than two hours, but I can't, is there a solution? (WiFi works on the kde plasma desktop)

**Comment by gh0stzk** [comment]
What do you use to connect in KDE?

My dotfiles do not modify or interfere with any system configuration such as the internet connection.

The most likely thing is that kde loads some process or service for the connection, that's why I ask you how do you connect to the internet, with networkmanager or which one do you use?

**Comment by airi5609** [comment]
I simply use the typical button to see the network window and connect, but I understand that this cannot be done in BSPWM, so I tried using the terminal, but it didn't work

**Comment by airi5609** [comment]
Nvm, Reinstall endeavors, I reinstalled your configuration and for some reason now the wifi works, thank you very much anyway
