### ISSUE TITLE
Eww bar (system tray, music, calender) + is there a way to close pop up windows without clicking on the icon again

### ISSUE THREAD

**Issue by qbnil** [gh0stzk/dotfiles#185]
1) There are some issues i'm facing after last installation. The system tray is acting wierd a bit. on pamela and other themes
![image](https://github.com/gh0stzk/dotfiles/assets/130576530/4abf7306-ce48-47db-b700-f8a14ea7c366)
except for zombie and jan
![Shot-2024-01-22-100034](https://github.com/gh0stzk/dotfiles/assets/130576530/43233a20-262b-4cd7-addd-49a4232d0827)
2) Another thing that bothers me is mpd. Is it always blank like that. I mean, i know it'll work once i start playing downloaded music. But is it possible to play music which i play in browser?
![image](https://github.com/gh0stzk/dotfiles/assets/130576530/5b9c6529-b374-4096-a7e4-5f8201e3d57a)
3) There are some strange cases when the terminal appears straight up in my neovim 
![Shot-2024-01-22-100503](https://github.com/gh0stzk/dotfiles/assets/130576530/2e468efa-4ed0-4c65-9d80-679defc3523f) and i'm able to run any command. Well, it could be a feature tho, lol, to not have telescope but still be able to spin up those kind of windows. 
4) Another thing that annoys me is that i'm not able to close anything with esc key, which i clicked on from the eww bar, for example the music player which open up when i press on the music icon (and it's at the bottom which is also not good)
![image](https://github.com/gh0stzk/dotfiles/assets/130576530/18ab30c5-0c23-44c7-902e-0973e97bf2f1)
5) The calender position is a bit wrong too, it's moved to the left, i don't really know what causes that, but a buggy behaviour still
![image](https://github.com/gh0stzk/dotfiles/assets/130576530/1ce953ab-9cde-49f5-9694-d7f2b5fd3688)
Hope this is not a lot, but that's what i've noticed. Keep it up gh0stzk

**Comment by qbnil** [comment]
There is actually another thing i forgot to mention, the telegram startup time is slow as turtle, which is probably because of xdg-portal but i'm doubting that

**Comment by gh0stzk** [comment]
Hello, a lot of things but i try to help u in all the points.

- Only telegran opens slow? yes there is some error with the xdg-portal app in the WMS, but if it only happens with Telegram, it is probably something else, recently I read in some group this same problem with Telegram, they related it to Qt5 and the new Qt6 but I wouldn't know tell you more about it, I don't think it's a problem with my dotfiles if it only happens to you with Telegram. If it happens to you with more applications, it may be the problem related to xdg-portal.

- About your strange issue with neovim and the terminal, It is the first time that someone mentions this problem, of course it is something strange, I will investigate to see if I find something about it.
Are you using my neovim configuration? or is it another? is the terminal alacritty? Precisely today I deleted the neovim configuration from the repository, because I was working on a more complete and lighter one, maybe in a week or two I will upload it.

- Regarding the incorrect positioning of the system tray, it is something that occurs in different resolutions, unfortunately stalonetray does not allow you to configure the positioning in percentage, which would allow it to fit well in all resolutions.

But you can solve it as I mention in this comment https://github.com/gh0stzk/dotfiles/issues/173#issuecomment-1873009049

- About the fact that mpd always appears blank, if you have never played anything with mpd it will always appear like this, once you play something even if you are not playing anything at that moment you will always see the last song you played.
![Shot-2024-01-22-022430](https://github.com/gh0stzk/dotfiles/assets/67278339/355f9707-9cc7-40d5-8d0c-4f25d356cdd8)

Regarding that polybar module working with the browser or spotify, it is impossible, my dotfiles use the polybar mpd module, but you can always replace it and use another module, there are several, I will leave you some links, https://github.com/mihirlad55/polybar-spotify-module https://github.com/gh0stzk/dotfiles/issues/46#issuecomment-1482161297

- About your problem with the eww widgets, your first question is if they can be closed, with esc or with some button, I think the same thing is uncomfortable not being able to close them more easily, in a month my vacation will start and maybe I will redesign them with a button to close them. For now I'm sorry.

the calendar is out of place or you want the player in another position, you can edit its positioning by editing these two files.

~/.config/bspwm/eww/player/player.yuck
~/.config/bspwm/eww/calendar/calendar.yuck

In both files at the end, there is the geometry configuration, edit the x and y values ​​to your liking.

![Shot-2024-01-22-024858](https://github.com/gh0stzk/dotfiles/assets/67278339/68d72af0-47a8-43bd-99aa-1ea13c43056a)

**Comment by qbnil** [comment]
Thx, that was at least something and btw, yes i use your original dotfiles with neovim preconfigured by you, alacritty as it is
