### ISSUE TITLE
[Suggestion]: Please make update system

### ISSUE THREAD

**Issue by linoxolus** [gh0stzk/dotfiles#188]
reinstalling dotfiles often causes a lot of trouble, for example losing some of my config files, please create an update system that doesn't require reinstallation

update.sh?

**Comment by gh0stzk** [comment]
That would be a little difficult, if not almost impossible, because as you mention, your settings would be lost. I could make a script that replaces everything new added or modified, but the patch would still fail since the vast majority, if not all, modify the dotfiles. In the same way, there are no longer been any major changes.
