### ISSUE TITLE
[Request]: For Debian Users

### ISSUE THREAD

**Issue by R0ttCyph3r** [gh0stzk/dotfiles#189]
Hi there,

I really love your dotfiles and man you did a great job. This is a piece of art. These dots became my go to recommendation if any of my friend ask how they can customize.

But the problem is i am cyber security guy and i use Debian most of the time and all of my friends too so may i have your attention on this and please a config for Debian users it would be really helpful for us, much appreciated.

Thanks for the awesome rice man.

PS:
I kind off made it work on my debian but it only works in that vm and not able to replicate it so to make your work easier here's list of packages i installed after a bare minimum install of debian 12 (bookworm).

```
sudo apt install -y xorg xserver-xorg xbacklight xbindkeys xvkbd xinput build-essential vim bspwm sxhkd polybar alacritty make gcc dkms net-tools firefox-esr rofi picom thunar thunar-archive-plugin thunar-volman file-roller dialog acpi acpid policykit-1-gnome pulseaudio alsa-utils pavucontrol volumeicon-alsa pamixer neofetch lxappearance fonts-recommended fonts-ubuntu-title fonts-font-awesome fonts-terminus lsd nitrogen dunst libnotify-bin unzip curl slim mpv qimgv linux-headers-$(uname -r) brightnessctl jq bspwm polybar sxhkd alacritty dunst rofi jq policykit-1-gnome git playerctl mpd ncmpcpp geany ranger mpc picom xdotool feh ueberzug maim pamixer libwebp-dev xdg-user-dirs nala webp-pixbuf-loader zsh zsh-autosuggestions zsh-syntax-highlighting thunar thunar-volman thunar-archive-plugin gvfs gvfs-backends engrampa tint2 dmenu xdo jgmenu redshift xautolock fzf ytfzf yt-dlp gawk tumbler gpick neofetch xdg-utils python-is-python3 python3-gi gir1.2-nm-1.0 duf libglib2.0-bin btop ncdu bat exa wmctrl acpid xclip scrot acpi mpdris2 libplayerctl-dev gir1.2-playerctl-2.0 lxappearance bc libxcb-xinerama0-dev libxcb-icccm4-dev libxcb-randr0-dev libxcb-util0-dev libxcb-ewmh-dev libxcb-keysyms1-dev libxcb-shape0-dev
```

I hope this helps you

**Comment by gh0stzk** [comment]
Thanks, I'm glad you like my dotfiles, and that you modify them.

Yes, I have plans to add an installer for fedora and debian, it is a lot of work but a friend from a Facebook group who uses my dotfiles already did the hard work. It's not just installing the environment, it's modifying the scripts like the "update" one in polybar, changing the launcher icon, depending on the OS, for example, etc.. etc.

The time I have for now is limited due to work, but in the meantime I already have a debian in a VM and there I am starting to correct and add things. When I have time, I will install Debian on real hardware and then publish the changes.

**Comment by R0ttCyph3r** [comment]
okay bro i will be waiting until then i will also try to make them work on debian everything worked out i will tell you
