### ISSUE TITLE
Multi desktop with eww

### ISSUE THREAD

**Issue by 0xN1nja** [gh0stzk/dotfiles#207]
I have successfully installed the new rices and migrated old themes to the new one. Everything is done now.

However, I'm encountering issues with eww bars of andrea and z0mbi3 rice. The problems lies in the `launch_bars` function (Theme.sh), where proper iteration over the monitors list is not being performed:

```bash
launch_bars() {
	eww -c "${rice_dir}"/bar open --toggle bar
	polybar -q tray -c "${rice_dir}"/bar/polybar_tray.ini &
}
```

This should have been implemented as you did in other rices (with no eww bar):

```bash
for mon in $(polybar --list-monitors | cut -d":" -f1); do
		MONITOR=$mon polybar -q cata-bar -c "${rice_dir}"/config.ini &
done
```

However, I am unsure how to render eww components on secondary monitors by iterating. After some research, I came across this issue: https://github.com/elkowar/eww/issues/519, where it was suggested that rendering could be extended to the second desktop by passing `--screen 1`.

Unfortunately, this approach did not yield the desired results; the rendering was either confined to the first monitor and didn't appear on the second monitor.

Whenever I connect an external monitor, the eww bar (with or without `--screen 1` flag) displays an odd result (I don't know if it is intended or not):

![image](https://github.com/gh0stzk/dotfiles/assets/71812498/65cf660a-d965-4c76-9917-e8add3e4aefa)

**Comment by 0xN1nja** [comment]
The second issue, though not quite an issue but rather a question; is how the polybar handles the system tray.

Occasionally, I notice that the discord icon (systray) sometimes appears on my primary desktop, while at other times it appears on the secondary one (completely random). After conducting some research, I came across this issue: https://github.com/polybar/polybar/issues/1070. 

For example:

![image](https://github.com/gh0stzk/dotfiles/assets/71812498/542ee701-a9b1-486f-9ed9-0690513161a7)

The left screen is my primary monitor, while the right one is an external monitor.

I am still uncertain whether this behavior is intentional or not.

**Comment by 0xN1nja** [comment]
The third issue is with the introduction of the tray module in polybar, which makes `tray-position` obsolete.

Its alignment is flawed in some rices; such as in Cristina:

![image](https://github.com/gh0stzk/dotfiles/assets/71812498/eceb92ff-cf62-4d3a-bf8d-31e07f820153)

So should I stick with the previous option? (the `tray-position` one)

**Comment by 0xN1nja** [comment]
Last one, is with the 'music' widget, as I am unable to comprehend its functionality:

![image](https://github.com/gh0stzk/dotfiles/assets/71812498/b8d95e1a-b380-467e-9a6c-183f6feffc16)

Whenever I try to play something via mpd, it consistently displays the same window.

I am uncertain whether there is a specific action I am required to take; like am I supposed to press something?

**Comment by gh0stzk** [comment]
Of course I'll start from the last to the first.

The problem with the player, are you sure you are using the newest version of the script??? check your local file with this https://github.com/gh0stzk/dotfiles/blob/master/config/bspwm/scripts/MediaControl . 

Thats a weird issue, but im guessing you are using old script. Anyways be sure to configure mpd correctly https://github.com/gh0stzk/dotfiles/wiki/MPD-Configuration

---

About the tray position in cristina, i dont understand, compare your local files with the ones in the repo or maybe you modified, because i dont see the power buttom in your image, maybe you dont remove a "sep" module in config.ini

Must look like this:
![Shot-2024-03-21-071550](https://github.com/gh0stzk/dotfiles/assets/67278339/56e54ebe-d2c4-420d-a966-204e02026d29)

---

About discord icon in your second monitor or randomly location, Does it happen to you with any icon or just with the discord one???

Beyond that, it could be an expected error since my setup is made for one monitor, although you can configure more monitors https://github.com/gh0stzk/dotfiles/wiki/Two-or-more-monitors-setup still So polybar loads "the same" bar on the other monitors. Your setup should be modified to have another bar in config.ini and that bar is configured specifically for the external monitor.
I don't have another monitor, that's why I can't test code or add those types of setups.

In the link you left, there are some scripts and I have seen many more scripts that add the functionality you want. Basically to guide you on the right path, you need to define another polybar within config.ini, that polybar that is equal to the main one but you eliminate the tray module, and in the function that loads the polybar in theme.sh use the code from some script so that if it is the external monitor, that polybar is loaded there without the tray module.

---

The reason why your desktops were duplicated, from 6 to 12, is due to the WorkSpaces script within the z0mbi3/bar/scripts theme since you are duplicating the bar, the script is being executed 2 times and because of how it works internally, that it is the result.

Again, unfortunately, the workspaces script would have to be modified so that it works with more monitors, but try this, maybe it fix the duplication:

```bash
# Listen to bspwm changes
print_workspaces
bspc subscribe desktop node_transfer | while read -r _ ; do
    print_workspaces &
done
```
Remove the "&" in the last print_workspaces

**Comment by 0xN1nja** [comment]
Thank you for responding so quickly. Yeah, I forgot to copy my latest music script. After copying it, It started working.

<hr>

Regarding the Cristina rice, I haven't added the power button because it looks a bit odd on the polybar.

I tried adding a separator after the tray in the `config.ini`, but it didn't work because my main issue is that the icons of apps in the system tray (like Discord and Telegram) are not scaling properly:

![image](https://github.com/gh0stzk/dotfiles/assets/71812498/1365929b-82ed-45af-861c-f28841ae4cce)

<hr>

This issue occurs with any icon in the system tray; this is how I configured polybar (in every `config.ini`) as suggested by https://github.com/polybar/polybar/issues/763#issuecomment-331604987:

```ini
[bar/emi-bar]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false
```

```bash
launch_bars() {
	for mon in $(polybar --list-monitors | cut -d":" -f1); do
		MONITOR=$mon polybar -q emi-bar -c "${rice_dir}"/config.ini &
	done
}
```

Another thing I noticed is that the 'update' module displays available updates on a single screen, while on the other screen, it shows 0 updates.

![image](https://github.com/gh0stzk/dotfiles/assets/71812498/8ecddcf5-26c5-422a-a958-2b16af5c0f1b)

Am I missing something here? Or is it related to Polybar? I will create an issue in the polybar repo then.

<hr>

I modified the workspace script (both in andrea and z0mbi3), but it didn't work; workspaces were still duplicating. 

But the thing is, I want the eww bar to appear on every screen, just like the polybar. Is it possible? I also provided a link in one of my previous comments, https://github.com/elkowar/eww/issues/519, where it was suggested that rendering could be extended to the second desktop by passing `--screen 1`, but I don't think it is possible to render the bar on both monitors.

**Comment by gh0stzk** [comment]
about the icons in systray, did you tried to edit in modules.ini the module tray this option:
tray-size = 72% change the value, 63% is the default one. that bar is very small, look normal but there is a border, border makes the bar looks bigger but is small for the space for modules.

**Comment by gh0stzk** [comment]
About your problems with second monitor, is hard for me to help you, because i dont have a second monitor.
did u try for eww bar this: in eww.yuck in z0mbi3/bar look for the final of the file

```
(defwindow bar
	:geometry (geometry :x "15px"
						:y "0%"
						:anchor "left center"
						:height "86%"
						:width "47px")
						
	:reserve (struts :distance "5px"
					 :side "left")
	:wm-ignore false
	(bar))
```
first add monitor 0

```
(defwindow bar
        :monitor 0
	:geometry (geometry :x "15px"
						:y "0%"
						:anchor "left center"
						:height "86%"
						:width "47px")
						
	:reserve (struts :distance "5px"
					 :side "left")
	:wm-ignore false
	(bar))
```

then copy the code and change windows name and monitor to this

```
(defwindow bar-external
        :monitor 1
	:geometry (geometry :x "15px"
						:y "0%"
						:anchor "left center"
						:height "86%"
						:width "47px")
						
	:reserve (struts :distance "5px"
					 :side "left")
	:wm-ignore false
	(bar))
```

then in theme.sh try somithing like this

```bash
# Show bar on laptop screen
eww open bar --screen 0

# Show bar on external screen if connected
NB_MONITORS=$(hyprctl monitors -j | jq length)
if [ "$NB_MONITORS" -eq "2" ]; then
    ## hyprctl dispatch focusmonitor 1
    eww open bar-external --screen 1
fi
```
obviously change the hyprctl command for the one in bspwm to list monitors

**Comment by gh0stzk** [comment]
about the polybar and update script dont know, maybe yes is a bug in polybar, if you reload polybar in second monitor this fix the issue?

**Comment by 0xN1nja** [comment]
Yeah, setting `tray-size = 72%` works perfectly, even `80%` works fine too. But I still prefer rendering the systray in the old way (by not creating a module `tray` in modules.ini).

<hr>

And that code snippet works perfectly!

![image](https://github.com/gh0stzk/dotfiles/assets/71812498/d169ce03-3226-4320-995c-99bb68b0aa66)

I'll extend this in andrea rice as well, and then I'll give you the code after testing.

<hr>

The only issue in polybar is with the systray and update script; otherwise my config is completely stable (until you push something new). I'll dive deeper and create an issue in the polybar's repo this week.

<hr>

One last thing; is with padding of next button in andrea rice on the music widget:

![image](https://github.com/gh0stzk/dotfiles/assets/71812498/0dcfa8d4-11da-4dae-8403-581f332a7a97)

And also, the `check-network` script isn't returning the SSID:

![image](https://github.com/gh0stzk/dotfiles/assets/71812498/58da90d6-4ca4-4ff5-8657-19b6c69f8efa)

The SSID for my wifi isn't showing up properly on the bar.

**Comment by gh0stzk** [comment]
In just a few minutes I am going to push the update that integrates the rofi menu to manage connections, and that error that you mentioned in Andrea that does not return the ssid is corrected.

**Comment by 0xN1nja** [comment]
what about the padding of next button?

**Comment by gh0stzk** [comment]
> what about the padding of next button?

Oh yes, in ~/.config/bspwm/rices/andrea/andy/eww.yuck

on line 148 search for "󰓛 " just remove the extra space, to this "󰓛"

**Comment by 0xN1nja** [comment]
Hey @gh0stzk, regarding the `update` module issue mentioned in https://github.com/gh0stzk/dotfiles/issues/207#issuecomment-2015833711, I asked the maintainer of polybar and they said that the issue is with the `Update` script itself:

https://github.com/polybar/polybar/issues/3127

Could you please take a look?
