### ISSUE TITLE
File managers Issue (Thunar, Dolphin) - Tiling, Theme

### ISSUE THREAD

**Issue by ChrolloRifat** [gh0stzk/dotfiles#210]
Thunar always opens up with a  pseudo-tiled style, which makes it shorter in height when multiple windows are opened. How to make it properly tiled by default instead of pressing meta + T everytime? Also, no matter what theme i choose, dolphin always have light and dark color mismatch,for example, some side is light colored and some are dark which makes it look disgusting. is there a way to make dolphin consistent with the rest of the dark theme scheme we have in our rice?

**Comment by gh0stzk** [comment]
Yes its because there is a rule in for thunar. You can edit/delete in ExternalRules file in ~/.config/bspwm/scripts/ search for:

``` bash
Thunar)
 result "state=pseudo_tiled desktop=^2 rectangle=966x576+0+0 follow=on"
;;
```

You can delete it or edit it, you can leave as is, just deleting the state and rectangle

``` bash
Thunar)
 result "desktop=^2 follow=on"
;;
```
In this way, thunar still open in desktop 2 and you will follow thunar when you open it.

--- 

Yes about the apps that open with a theme that does not follow the colors scheme of the rice it is in. It's because the only thing that doesn't modify my themes is the gtk or qt appearance.

Because imagine making 15 gtk themes, and having you download them in the installer, my dotfiles would have a size greater than 200 or more megabytes. And it's not my intention,

To modify the gtk theme manually you can use lxappearance, for qt applications, the truth is I have never used many qt applications, they are almost always gtk and I wouldn't know how to change the theme.

**Comment by ChrolloRifat** [comment]
Thank you so much, man.
