### ISSUE TITLE
how to make my display to 1920x1080

### ISSUE THREAD

**Issue by hdgetban** [gh0stzk/dotfiles#218]
dotfiles works perfectly fine i just copied it on my linux mint and its working but the display is small i wanna make it to 1920x1080 so how can i do that?

**Comment by gh0stzk** [comment]
it is a fresh install?? did you configure your screen?? you can use xrandr or arandr... apart of that there must be a lot of errors in polybars, starting from the updates module only work for arch..

**Comment by hdgetban** [comment]
i tried to use xrandr and arandr and none of those work and is not fresh installed

**Comment by hdgetban** [comment]
its been like 2 month using linux mint

**Comment by gh0stzk** [comment]
The only thing I can think of is that there is a background service configuring your resolution, since it is not arch and I have not used mint for more than 15 years, xrandr or arandr should work for you, if they don't it is because there is an error Or as I mentioned there is "something" in the background configuring or preventing the configuration of your resolution.

About my dotfiles, The bars (polybar, eww) adapt to your resolution, they are set in percentage, it must be something related to your monitor/resolution settings.

Even 1920x1080 is a higher resolution than I set my dotfiles at, I did it at a resolution of 1600x900, yours should look even better.

This screenshot is from my laptop with a resolution of 1366x768 and looks fine.

![Shot-2024-04-03-115355](https://github.com/gh0stzk/dotfiles/assets/67278339/a88b8e28-782b-45be-9c6c-6aabe0ad1187)

If u do `xrandr --output HDMI-1 --mode 1920x1080` it changes?? obviously change HDMI-1 for yours.

**Comment by hdgetban** [comment]
![Shot-2024-04-03-210542](https://github.com/gh0stzk/dotfiles/assets/156936988/b8b8b71d-28ef-4360-b1fe-8e423b321e6a)

HDMI-1 didnt work but i tried eDP-1 and it worked it made my screen 1920x1080 thanks dude and btw your dotfiles are soo good

**Comment by hdgetban** [comment]
and btw what package do i need for the screen to lock

**Comment by gh0stzk** [comment]
My dotfiles uses physlock in arch you can install with physlock package, in other distros i dont know.

**Comment by hdgetban** [comment]
done i installed it thanks you can close this
