### ISSUE TITLE
New eww 0.6.0 breaks powermenu and calendar widgets.

### ISSUE THREAD

**Issue by Zirox121** [gh0stzk/dotfiles#233]
Hace poco hice una instalacion en limpio, pero me está dando un error en los iconos de apagado, reinicio y salir. ¿hay forma de repararlo?
![Shot-2024-04-21-201221](https://github.com/gh0stzk/dotfiles/assets/146961720/8d1edb89-c167-413e-8a18-4d3c629d7bd3)

**Comment by gh0stzk** [comment]
Asegurate de tener instalada la fuenta font awesome, tal vez por alguna razon el proceso en el instalador, fallo o algo ... 

En tu carpeta ~/.local/share/fonts deberia estar

![Shot-2024-04-21-225132](https://github.com/gh0stzk/dotfiles/assets/67278339/cdb71786-daeb-4a5f-97d7-32260eb9d570)

otro podria ser que el demonio eww fallo, ejecuta `pkill eww`  despues vuelve a dar al icono para abrir ese menu y mira si se soluciono.

**Comment by Zirox121** [comment]
Solo con esos, ¿Habría forma de reinstalarlos?
![Shot-2024-04-21-233824](https://github.com/gh0stzk/dotfiles/assets/146961720/c621e582-6789-4e35-8bed-ef1698e67f6d)

**Comment by gh0stzk** [comment]
Acabo de ver que eww lanzo una nueva version ayer, voy ahora a compilarla e instalarla y comprobar si por ahi esta el error y necesito hacer cambios.

Por mientras pues si es un error un poco raro...

**Comment by gh0stzk** [comment]
Efectivamente, es relacionado a la nueva version de eww, ya que presento el mismo error que tu, por el momento tendras que esperar 2 o 3 dias en lo que lo soluciono.

**Comment by gh0stzk** [comment]
I already create an issue in the eww repo https://github.com/elkowar/eww/issues/1083 

I already fix the calendar widget adding :show-truncated "false" to labels. But power menu is still broken. i will merge the fix for calendar now. This does not affect people who had eww installed before yesterday.

And it is not necessary to update eww either, however they have already added the systray widget and in the not too distant future, I will be adding it to rice z0mbi3 and andrea. and then you need to update eww.

**Comment by gh0stzk** [comment]
Problem fixed.

Solo clona el repo de nuevo y copia los archivos ~/.config/bspwm/eww/powermenu/powermenu.yuck a donde corresponde.

**Comment by Zirox121** [comment]
Gracias!!!
