### ISSUE TITLE
bag eww player after nvidia driver

### ISSUE THREAD

**Issue by rom17** [gh0stzk/dotfiles#246]
![Shot-2024-05-14-170201](https://github.com/gh0stzk/dotfiles/assets/97874213/ee50abeb-fcaa-4365-b077-ad7cfb01774c)

**Comment by rom17** [comment]
flickering white squares

**Comment by gh0stzk** [comment]
What a beautiful bar you have!!!

About your error, I don't think I can do anything, because it seems to be a problem with the Nvidia graphics, I don't think it's even an eww problem, maybe a problem with picom would be safer to assume.

Try this, open the picom configuration, ~/.config/bspwm/picom.config

and change the glx backend to xrender, save it, and kill the picom process, `pkill picom`. Then restart bspwm with `super + alt + r` and see if it fixes it.

Maybe you want to create an issue on the picom github https://github.com/yshui/picom

**Comment by rom17** [comment]
ок  
not so important... I'll try it with peak, it's worth glx, I'll try changing it to something else... your configs with minimal changes are great

**Comment by rom17** [comment]
xrender  also messes up... not so important.

**Comment by gh0stzk** [comment]
What a shame that didnt work, i cant help you more because i use amd radeon and an intel graphics in others pcs. I dont have nvidia.

Stay tuned for bugs in Mesa and Nvidia, Mesa was recently updated as well. I'm sure you won't be the only one with problems with Nvidia.

**Comment by rom17** [comment]
thanks for the answers and attempts to help
