### ISSUE TITLE
I can't connect to Bluetooth due to notification

### ISSUE THREAD

**Issue by gr33pp** [gh0stzk/dotfiles#250]
Pairing request requires a button to be clicked when notification comes up, but here there's no button to actually accept the pairing request. I will be glad if you can help me.

**Comment by gh0stzk** [comment]
Yes, I know exactly what your problem is, I had the same one, no matter how much I searched for a solution, I couldn't solve it, according to the dunst github, I have the correct options enabled in the configuration, but the accept dialog is never shown in the notification.

Precisely these days, I am finishing a rofi menu to manage Bluetooth connections, and a polybar module.

But in the meantime you will unfortunately have to manually add your device to the trusted list.

You now how to do it? or need help?

Another solution is installing xfce4-notifyd, then kill dunst

```
sudo pacman -S xfce4-notifyd
killall dunst
/usr/lib/xfce4/notifyd/xfce4-notifyd &
```

with this you will be using xfce4 notifications and now try again adding your device. this will help for now, i promese to find a definitive solution.

**Comment by gr33pp** [comment]
I used `bluetoothctl` to pair. The blueman gui has no issues connecting after that.. I'm going to keep doing that until you have a fix. I love your work bro. ♥️♥️.
