### ISSUE TITLE
Eww Bar resize Issue and Small query

### ISSUE THREAD

**Issue by ShadeZerox** [gh0stzk/dotfiles#251]
So basically, whenever i hover on powermenu option in the sidebar, it would increase in size and stay that way. And after that if i hover over it again, it won't increase any more. Though sometimes it bugs and increases more than the screen size on hovering multiple times.

Before Hovering:
![image](https://github.com/gh0stzk/dotfiles/assets/155251572/3c734bed-51bf-4f73-a883-df38865c9f83)
After Hovering:
![image](https://github.com/gh0stzk/dotfiles/assets/155251572/6a53eba9-b74a-4180-88f6-6d452ba57bed)

Now my question is that is there anyway i could set this bar's minimum and maximum height? so that it doesn't stay too small not too big, just good enough to match the app windows. 
Secondly I wanted to know if there is any way for me to set rofi app launcher sorting from alphabetic to recently used? 
Lastly, I checked the eww config for profile widget and found nothing much there (I barely have any knowledge about eww),  so is there anyway to change the pfp there? I did try setting up an value for the IMAGEP env variable mentioned there, not sure if that does anything

**Comment by gh0stzk** [comment]
Hello, about your error with the bar in the z0mbi3 theme, it is a well-known "bug" in quotes because it is not a bug as such, it is the way gtk works, by not having space it lengthens, modifying the length of the bar is solved, another solution is to press the `super + alt + h` keys to hide the bar, then press `super + alt + u` to show it again and it will have its original size.

In the eww repository itself they mention that it is not a bug, this is how gtk and css work with eww.

To modify your bar to your liking, open the file ~/.config/bspwm/rices/z0mbi3/bar/eww.yuck and at the end of everything look for line 262 and change the 90% for a larger percentage, maybe 95% , try to the point where you no longer get that error.

About your rofi question, yes there is a way, open ~/.config/bspwm/scripts/Launcher.rasi the search for this line:

`disable-history:            true;`

Change trur for false and you are done.

About the profile image, no need to change code, just change the image in ~/.config/bspwm/assets/profile.png  give it the same name and extension, **profile.png** 

There is no need for it to be the same size, but it must be similar, do not add an image that is 5 times larger because the design will move and you will have to make modifications to the code.

**Comment by ShadeZerox** [comment]
Well i ended up playing around with your configs and somehow fixed the bar by (kind of?) disabling the system tray in eww bar.
And yeah rofi and profile picture now work as intended, everything is fixed. Thanks!
