### ISSUE TITLE
Rofi font size | change manually

### ISSUE THREAD

**Issue by qbnil** [gh0stzk/dotfiles#260]
Hey, is there any way i can change the default rofi font size (with their icons respectfully) from 9 to 12 for example. I tried changing it in Launcher.rasi but everytime i reload bspwm, it reverts back. Seems like the config gets ovewritten on every reload somehow
The same thing about the eww bar, changing the font size permanently

**Comment by qbnil** [comment]
The same thing about the eww bar, changing the font size permanently

**Comment by gh0stzk** [comment]
Hello, yes if you edit ~/.config/bspwm/scripts/Launcher.rasi everytime you reload or change a theme, it will be overwrite.

Yo need to edit the Theme.sh file inside the theme directory, for example, ~/.config/bspwm/rices/emilia/Theme.sh

in line 206 :

`-e '22s/\(font: \).*/\1"JetBrainsMono NF Bold 9";/' \`

Just change the 9 for other.

And the other question, what eww bar? in what rice??

**Comment by qbnil** [comment]
> Hello, yes if you edit ~/.config/bspwm/scripts/Launcher.rasi everytime you reload or change a theme, it will be overwrite.
> 
> Yo need to edit the Theme.sh file inside the theme directory, for example, ~/.config/bspwm/rices/emilia/Theme.sh
> 
> in line 206 :
> 
> `-e '22s/\(font: \).*/\1"JetBrainsMono NF Bold 9";/' \`
> 
> Just change the 9 for other.
> 
> And the other question, what eww bar? in what rice??

the daniela rice

**Comment by qbnil** [comment]
i'ma ask another question here, ig there is no need for opening another issue: there is something wrong with fetch size, everything gets crippled on open:
![image](https://github.com/gh0stzk/dotfiles/assets/130576530/65c45471-6e20-4b2c-bfb4-7e1aef0993d7)

**Comment by gh0stzk** [comment]
Hello about the fetch, I guess from what I see in the terminal font size, you increased it. The size of the floating window that opens when the fetch is displayed is preset, if you want to change it to be larger and fit the size of your font, change the size of the window, you can do it from .config/bspwm /scripts/Term file, find line 78 and change `initial_window_width=394` `initial_window_height=580` for a larger size width and height.

About daniela bar, is polybar, you can change the font size in .config/bspwm/rices/daniela/config.ini file, line 67, change the 13, for a bigger number.

**Comment by qbnil** [comment]
thx for your time and help. One huge question tho: Are you planning on implementing the dark version of andrea theme, because i know a lot of people want it to happen? (it looks fantastic in white, it'll surely be even more popular in dark colors)

**Comment by qbnil** [comment]
And the last question until we close the issue, i noticed some delay with updating the sound percentage in adrea theme. The notification is instant whereas the update in the eww bar comes with a bit of a delay about 0.3ms

**Comment by gh0stzk** [comment]
Hello, the eww variable "defpoll :interval" It is configured at 1 second, the default value I think is 2 seconds. Since you change the volume, the change is reflected in the interval of one second maximum. This is how eww works, maybe by modifying the defpoll in .config/bspwm/rices/andrea/andy/eww.yuck lines 25 and 26, is "1s" s for seconds, m for minutes, h for hours, but I don't remember if it exists for milliseconds or maybe doing "0.50s" but strictly answering your question, there will almost always be a delay from the action that is reflected, since the action does not always coincide with the internal interval that eww has.

About the other question, i didnt think to make a dark version, but you always edit colors in eww.scss inside the same directory i give you before.

ahh another thing, reducing the time interval will cause more requests to be sent, this on non-powerful or old computers will be reflected in higher cpu consumption

**Comment by qbnil** [comment]
gotcha, you made it clear, thx once again, keep the grind up
