### ISSUE TITLE
We need a clipboard tool

### ISSUE THREAD

**Issue by chrollorifat** [gh0stzk/dotfiles#262]
I recommend using cliphist as our clipboard tool. Recently I've been running in the need for a clipboard tool as I constantly need to do copy and paste in my codes and stuff. I'm pretty sure others might want it too. So can we up a script or something for it?

**Comment by 0xN1nja** [comment]
+1

**Comment by gh0stzk** [comment]
It's on my list of things to do. Possibly it will be added in the next update.

For now the next update will have:

- 2 new themes
- Bluetooth manager (rofi)
- Screenshot manager (rofi)
- The clipboard with rofi, I have 2 options, this one https://github.com/erebe/greenclip and this one https://github.com/yusufaktepe/rofi-gpaste  
- I Change the structure of the dotfiles a little instead of being ~/.config/bspwm/scripts/ now it will be ../src/ instead of scripts and inside there will be some new directories to store the rofi themes and others.. 
And maybe I'm forgetting something...

This is what I have done so far, possibly in 2 or 3 weeks I will upload the update, since work has me busy and I have not had time for this project.

**Comment by gh0stzk** [comment]
> cliphist

Cliphist works for wayland, not for x11.

**Comment by chrollorifat** [comment]
i'm really excited for the upcoming updates...
