### ISSUE TITLE
Systemtray gone?!?!

### ISSUE THREAD

**Issue by cowboycamilo** [gh0stzk/dotfiles#282]
Hi! great Job!!!
I update to your latest config, but I lost the system tray... there is no stalone drop down any more and I can't get to my tray...
Thanks for the help.

**Comment by gh0stzk** [comment]
Hi, yes stalonetray is not part of my dotfiles anymore, the native polybar and the new eww tray system are used in the z0mbi3 bar.

If for some reason, the systemtray does not appear in polybar, it is probably because there is another tray system in the background, check if stalonetray is not running in the background.
