### ISSUE TITLE
bluetooth error 

### ISSUE THREAD

**Issue by mrstretch** [gh0stzk/dotfiles#286]
how to remove the bluetooth error message
![image](https://github.com/user-attachments/assets/6abe3618-0ea7-41f6-b3c3-590ce22e3475)

**Comment by gh0stzk** [comment]
Open file ~/.config/bspwm/src/bluetooth.sh

After the shebang add this 

```bash
if ! command -v bluetoothctl; then
    exit 0
fi
```

or remove the module in config.ini, but the code to add is a general solution, not only for one theme.

Thanks i will commit the fix right now.

**Comment by AlvinPix** [comment]
Try installing these packages.

```
sudo pacman -S bluez bluez-utils blueman
```

 Enable the services 

```
sudo systemctl enable bluetooth
sudo systemctl start bluetooth
```

**Comment by mrstretch** [comment]
thanks you it’s fixed

**Comment by gh0stzk** [comment]
Yep but the problem is that bluetooth module is active in almost all rices, and if you doesnt hqve a laptop or a pc with bluetooth, there is the problem, i dont know why i didnt test this in my pc desktop, probably i only test in my laptop, but that code fix the problem for now, later i will improve it.

**Comment by mrstretch** [comment]
ok thanks,now I have no more errors
