### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by Skrap127** [gh0stzk/dotfiles#289]
Hello, first of all, congratulations on your work. I have been using your desktop environment for a while and have encountered some minor issues:

1. **Wallpaper Selection**: The error occurs when overwriting a wallpaper. When accessing the menu to select the wallpaper, the thumbnail of the previous background appears (although the correct wallpaper is applied when selected). Here is an example of what I mean:

![1](https://github.com/user-attachments/assets/57ac9bda-890d-46b9-b127-e3b2f9bb57e5)

2. **Andrea rice**: In the Andrea rice, part of the polybar does not display on the screen.

![Shot-2024-08-10-144518](https://github.com/user-attachments/assets/205dd9f3-29a4-4df8-9c82-c023b288f112)

3. **RAM Usage Percentage**: I have noticed that the RAM usage percentage does not match what is shown in other tools like htop or neofetch.

![3](https://github.com/user-attachments/assets/29da5dc5-0692-4c8c-a5d1-ae6d89fe4073)

4. **Bluetooth Module**: This is the issue that prompted me to open the topic. The Bluetooth module in the polybar does not work correctly. The actions to scan for devices and turn off Bluetooth do not execute, although other options, such as connecting to an already paired device (with blueberry), work correctly.

5. **Applications**: In some applications that use dropdown menus, they do not display in the correct location when selected.

![Shot-2024-08-10-145811](https://github.com/user-attachments/assets/e5818ebd-250c-4b2e-a54a-fb211e092467)

These are some of the issues I have encountered. I like your project and would like to use this environment daily. I would appreciate your guidance on resolving these issues, as fixing them would enhance the user experience, even though they do not affect the system's functionality. **Suggestion**: It would be great if you could implement a mode where options can be switched between two connected screens, such as only the main screen, only the secondary screen, etc., just like in other common environments.

**Comment by gh0stzk** [comment]
Hello, excellent post, I will try to solve it.
1. **Wallpaer Selection** The error occurs because since the image has the same name, the script understands that that image was already generated in the cache and does not cache it again.

The easy and quick way to solve it is to delete the folder in the cache directory ~/.cache/**yourusername/ricename**/ or if you do not want to delete the entire directory, just delete the image with the problem and when you run the script again it will cache it again .

The other solution from my side is to implement or modify the way the images are generated, so that the script only searches for changes in the file and thus will not be based only on the name of the image.

I put it on my to-do list.

2. **Andrea Rice** Well yes, I suppose you use a resolution lower than 1600x900 or what is your resolution?

That bar is made with "eww", and its size is in percentage, basically all the bars in the other themes although they are made with polybar, also its size is in percentage, the problem is not the size since they are in percentages. The problem is the content.

From my side, there is not much I can do, but if you can, maybe remove content, to test, for example we are going to remove 2 icons from the second bar, the Telegram one and the editor one.

Open the file ~/.config/bspwm/rices/andrea/andy/eww.yuck

From lines 90 to 100 is this code;

``` eww
(eventbox :cursor "pointer"		  
			(button :style "background-image: url('images/notes.png');"
					:class "icons"
					:valign "center"
					:onclick "OpenApps --editor &"))
			
			(eventbox :cursor "pointer"		  
			(button :style "background-image: url('images/telegram.png');"
					:class "icons"
					:valign "center"
					:onclick "OpenApps --telegram &"))
```
Delete that code or comment it, to comment code in yuck language it is with ";". Put 2 ;; at each beginning of line from 90 to 100 or delete it and then you can do undo. save it the file and the bar will change, You will surely notice that it already aligns correctly to your screen.

When the content exceeds the size of the bar, that's why you see it like this. But if you remove content, you will see it correctly.

3. **Ram indicators** Yes, it is totally normal that you see different numbers, it is because some applications use MiB other Mb. Even the polybar module shows a different larger one, because if I am not mistaken, polybar takes the used memory and also the cached one and shows you the sum. But ehm it's normal, there's nothing wrong.

4. **Bluetooth** Could you pls launchj the script from terminal, open a terminal and write `rofi-bluetooth` and do whatever you do to connect or pair devices, and se if the terminal shows errors and paste here.

thats not my script the repo is https://github.com/nickclyde/rofi-bluetooth for sure if there are errors, there could help you more than me, but paste your log error here and i will try to help you.

5. Is in all apps or just in specific apps? i didnt notice that in gtk apps or qt apps, what app is in your image? a windows app running with wine or something?

Yes, I want to improve multi-monitor support, but the problem is that I don't have a second monitor, I wouldn't dare put code that I haven't tested, but I'll probably buy another one this year, and then I will.

**Comment by Skrap127** [comment]
I have solved problems 1, 2, and 3 thanks to your help. Regarding problem 4, this is what the terminal shows when trying to pair a new device (In Blueberry, the device I want to pair does appear)

`Scan: off
Scanning...
SetDiscoveryFilter success`

and this when trying to turn off Bluetooth... 

`[CHG] Controller DC:85:DE:D9:C0:A2 PowerState: on-disabling
hci0 new_settings: powered bondable ssp br/edr le secure-conn
hci0 class of device changed: 0x000000
hci0 new_settings: bondable ssp br/edr le secure-conn
[CHG] Controller DC:85:DE:D9:C0:A2 Discoverable: no
Changing power off succeeded
[CHG] Controller DC:85:DE:D9:C0:A2 PowerState: off
[CHG] Controller DC:85:DE:D9:C0:A2 Powered: no
[CHG] Controller DC:85:DE:D9:C0:A2 Discovering: no
[CHG] Controller DC:85:DE:D9:C0:A2 Class: 0x00000000 (0)
[CHG] Controller DC:85:DE:D9:C0:A2 PowerState: off-enabling
hci0 class of device changed: 0x6c010c
[CHG] Controller DC:85:DE:D9:C0:A2 Class: 0x006c010c (7078156)
hci0 new_settings: powered bondable ssp br/edr le secure-conn
Changing power on succeeded`

I emphasize that these actions are not executed. 

**5.** The application I am showing is Matlab, which I installed following the steps provided on the official page. I believe it is a GTK application. Here is what the terminal outputs when running it: 

`MATLAB is selecting SOFTWARE rendering.
Gtk-Message: 15:50:11.284: Failed to load module "canberra-gtk-module"
libva error: dlopen of /usr/lib/dri/iHD_drv_video.so failed: /usr/local/MATLAB/R2024a/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /usr/lib/dri/iHD_drv_video.so)
MESA-LOADER: failed to open crocus: /usr/local/MATLAB/R2024a/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/crocus_dri.so) (search paths /usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open kms_swrast: /usr/local/MATLAB/R2024a/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/kms_swrast_dri.so) (search paths /usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open swrast: /usr/local/MATLAB/R2024a/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri, suffix _dri)`

The application works normally in the KDE Plasma environment.

**Comment by Skrap127** [comment]
I have solved problems 1, 2, and 3 thanks to your help. Regarding problem **4**, this is what the terminal shows when trying to pair a new device (In Blueberry, the device I want to pair does appear)

```
Scan: off
Scanning...
SetDiscoveryFilter success
```

and this when trying to turn off Bluetooth:

```
[CHG] Controller DC:85:DE:D9:C0:A2 PowerState: on-disabling
hci0 new_settings: powered bondable ssp br/edr le secure-conn
hci0 class of device changed: 0x000000
hci0 new_settings: bondable ssp br/edr le secure-conn
[CHG] Controller DC:85:DE:D9:C0:A2 Discoverable: no
Changing power off succeeded
[CHG] Controller DC:85:DE:D9:C0:A2 PowerState: off
[CHG] Controller DC:85:DE:D9:C0:A2 Powered: no
[CHG] Controller DC:85:DE:D9:C0:A2 Discovering: no
[CHG] Controller DC:85:DE:D9:C0:A2 Class: 0x00000000 (0)
[CHG] Controller DC:85:DE:D9:C0:A2 PowerState: off-enabling
hci0 class of device changed: 0x6c010c
[CHG] Controller DC:85:DE:D9:C0:A2 Class: 0x006c010c (7078156)
hci0 new_settings: powered bondable ssp br/edr le secure-conn
Changing power on succeeded
```

I emphasize that these actions are not executed.

**5.** The application I am showing is Matlab, which I installed following the steps provided on the official page. I believe it is a GTK application. Here is what the terminal outputs when running it:

```
MATLAB is selecting SOFTWARE rendering.
Gtk-Message: 16:03:57.271: Failed to load module "canberra-gtk-module"
libva error: dlopen of /usr/lib/dri/iHD_drv_video.so failed: /usr/local/MATLAB/R2024a/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /usr/lib/dri/iHD_drv_video.so)
MESA-LOADER: failed to open crocus: /usr/local/MATLAB/R2024a/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/crocus_dri.so) (search paths /usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open kms_swrast: /usr/local/MATLAB/R2024a/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/kms_swrast_dri.so) (search paths /usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open swrast: /usr/local/MATLAB/R2024a/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri, suffix _dri)
```

The application works normally in the KDE Plasma environment.

**Comment by gh0stzk** [comment]
About your 5 point, sorry i dont have idea.

Yes you need to scan before and your device will appear, if this causes trouble, use an aproppiate app like blueman just one time, to pair devices, then is easy for the rofi applet to connect, disconnect etc.

**Comment by Skrap127** [comment]
I appreciate your help
