### ISSUE TITLE
How to change the dashboard date language? 

### ISSUE THREAD

**Issue by ArifulProtik** [gh0stzk/dotfiles#30]
I was searching for it. I could't find it, My default language is English. I am new to this ricing world. May be a dumb.  I am using zomb13 theme

**Comment by gh0stzk** [comment]
![06-febrero-23-093439](https://user-images.githubusercontent.com/67278339/217014849-b85fe350-9ba1-4e9b-97df-fbe68ee6a2c7.png)

Do you mean this part?

If yes, well, Do you have more languages ​​configured besides English?

It's strange because the code part to show the date is this:
```
(defpoll hour :interval "1s" `date +%H`)
(defpoll minute :interval "1m" `date +%M`)
(defpoll fulldate :interval "24h" "date '+%A, %d %B'")
```
It is a generic linux command that shows the date in the language in which your system is configured, If your system is configured in Portuguese, it will display the date in Portuguese, if it is configured in Spanish, it will display it in Spanish, if it is configured in English, it will display it in English.

Try this code in a terminal `date '+%A, %d %B'`  It should show the date in your main language, in your case English.

**Comment by ArifulProtik** [comment]
Thanks ! for the clarification, it is actually showing in Portuguese, But I can't recall ever setting any system language beside English. Perhaps something went wrong on my end when running Riceinstaller Script. I should close the issue. And I really liked your work!
