### ISSUE TITLE
thank you for sharing. how do i start after the installation

### ISSUE THREAD

**Issue by shi4h** [gh0stzk/dotfiles#307]
![20240827140015](https://github.com/user-attachments/assets/bc1c7db9-d52f-43e2-9788-77169837c936)

**Comment by 0xN1nja** [comment]
run `startx`

**Comment by 0xN1nja** [comment]
yeah, install them.

**Comment by map588** [comment]
@0xN1nja  Once installed, startx just spawns the default xterm.  I am having the same problem as @shi4h.  Where exactly in this repo are you modifying a .xinitrc or something?  How does the installer script change the init sequence to launch xorg with bspwm?

**Comment by 0xN1nja** [comment]
add `exec bspwm` to `~/.xinitrc` then run `startx`

**Comment by 0xN1nja** [comment]
Did you install a display manager like `lightdm`? afaik the installer script doesn't install a display manager.

**Comment by map588** [comment]
No I did not.  That makes sense.  The reason I asked is because I had used this script on another machine and it worked great, even on Void linux! (with some modification), but it was not a clean install, and I had a display manager.  

So is having lightdm installed the "canonical" way of using this script?  and I definitely do not remember modifying my .xinitrc or similar, so I am concerned that the script is attempting to change the initialization of Xorg and I'm not aware of it.  Nothing is mentioned in the instructions afaik, it just says run the script. @0xN1nja

**Comment by 0xN1nja** [comment]
Install `lightdm`:

`sudo pacman -S lightdm lightdm-gtk-greeter`

and enable it on boot:

`sudo systemctl enable lightdm`

Then reboot.

**Comment by gh0stzk** [comment]
No, you do not need to have lightdm or any other login manager as a requirement. My script does not install or intervene with that. To install it is assumed that you already have a functional installation with the software of your choice.

**Comment by map588** [comment]
Would you mind writing that in the Wiki? @gh0stzk

**Comment by gh0stzk** [comment]
> Would you mind writing that in the Wiki or README instructions? @gh0stzk

Yeah i will add it.
