### ISSUE TITLE
dotfiles overwritten

### ISSUE THREAD

**Issue by Tom-jm03** [gh0stzk/dotfiles#308]
nice your script overwrote my whole dotfiles...
Maybe a check would be nice, if there already exists a directory named dotfiles...

**Comment by 0xN1nja** [comment]
The check already exists, the script creates backup of your existing config at `~./config-backup`.

**Comment by Tom-jm03** [comment]
Yeah, wow. One Folder called kitty something.

**Comment by gh0stzk** [comment]
oh yes that was a wtf moment!

I'm sorry about that, the script checks if a cloned folder called dotfiles already exists, and if so it deletes it assuming you are cloning the same dotfiles, since if not, it simply gives an error when cloning the repository. It's true that I can't predict all the different setups people have, possibly you had your dotfiles folder linked to the ../.config directory

**Comment by Tom-jm03** [comment]
Maybe create a file in the installing process with a specific value inside that is also in the repo.

Add a if that checks if the file exists in the dotfiles directory and if the file has the specific value in it.
If it does, the directory is your dotfiles one and you can safely erase it.

If it doesn't either the user deleted that file or it is not your repo, so the script breaks and tells you that a folder called dotfiles already exists and exits.

**Comment by Tom-jm03** [comment]
Ima make a pr tomorrow.
