### ISSUE TITLE
[BUG] no animations

### ISSUE THREAD

**Issue by depocoder** [gh0stzk/dotfiles#330]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

Hi, thank you for your repo. Have issue with animations. No animations at all. Rice editor haven't helped :(

### Expected behaviour

to have animation like in video on YouTube

### System information

I Installed pure Manjaro OS with open sources nvidia drives, disabled gnome by systemctl and installed additionaly this packages
```
sudo pacman -S xorg bspwm sxhkd xorg-xinit xterm git python3 && sudo pacman -S lightdm lightdm-gtk-greeter
```
First command for running bspwm itself, because your scripts didn't install it. Second, for using GUI to enter. 
I open rice editor toggle animation, clicked apply everywhere and even reboot but have no animations at all. 

My setup:
Two monitors, nvidia 4080 super i9 14. 

I don't think that it is NVIDIA problem because gnome is working good.

**Comment by gh0stzk** [comment]
Hello, what is the output from this command `picom --version` ??

All other things works fine??  could you add the log of ~/.xsession-errors file pls

**Comment by depocoder** [comment]
> Hello, what is the output from this command `picom --version` ??
> 
> All other things works fine?? could you add the log of ~/.xsession-errors file pls

Thanks for fastest reply! I found out it was 11 version. Few minutes ago installed from github and it is working!!! Can you add information about animation in wiki or auto install 12 version?

**Comment by depocoder** [comment]
@gh0stzk can you also say how to move windows from one monitor to another one?

**Comment by gh0stzk** [comment]
> Thanks for fastest reply! I found out it was 11 version. Few minutes ago installed from github and it is working!!! Can you add information about animation in wiki or auto install 12 version?

In think the problem was manjaro repos are still with v11, i dont know, my script install the official one from arch repos and its on v12 now.

about how to move, there is a cheatsheet when you press F1, but apparently eww is broken https://github.com/gh0stzk/dotfiles/issues/331 im just working on that now.

about how to move you need to configure your 2 monitors setup https://github.com/gh0stzk/dotfiles/wiki/Two-or-more-monitors-setup once you do that yo only need to move the window like normal `super + alt + (1-9)` that will move your window to specific workspace, if that workspace is on monitor 2, the app already be in monitor 2. Or on focused window press `super + alt + arrow keys` and the window will move throught workspaces and you follow.
