### ISSUE TITLE
Installer not working properly 

### ISSUE THREAD

**Issue by joelwoel** [gh0stzk/dotfiles#34]
I had to reinstall arch for some reason and now I can't install this again. When i run it, the script is executed and everything is installed but when i open bspwm, it's just empty. No theme, no wallpaper, the basic shortcuts are the so ig sxhkdrc is working. I couldn't get my fork to work so i rhought I must've messed something up but i tried yours and even this one doesn't

**Comment by gh0stzk** [comment]
i recently remove LaunchWorld script and all the conf is in bspwmrc but if you installed from 0 the script should work.

 one thing you can do is delete from ~/.config/ the bspwm, termite, lacritty, rofi, polybar, eww dirs, open a terminal and copy manually the files 

```
cp -r $HOME/dotfiles/config/* $HOME/.config
cp -r $HOME/dotfiles/misc/bin/* $HOME/.local/bin
cp -r $HOME/dotfiles/misc/applications/* $HOME/.local/share/applications
cp -r $HOME/dotfiles/misc/fonts/* $HOME/.local/share/fonts
cp -r $HOME/dotfiles/home/.zshrc $HOME
```

What shell are u using? bash or zsh ?

**Comment by joelwoel** [comment]
I deleted my config fiolder and then ran yours. But that didn't work. Idk if that counts as starting from zero or not. Also i was using zsh

**Comment by joelwoel** [comment]
Ok I'll try those and update.
I use lightdm login manager. And i also have i3 installed along with bspwm.

**Comment by joelwoel** [comment]
I checked ~/.xsession-errors and found this
```
cat: ~/.config/bspwm/rices/emilia/alacrittyrc: No such file or directory
~/.config/bspwm/scripts/LaunchWorld: line 32: ~/.config/termite/config: No such file or directory
~/.config/bspwm/scripts/LaunchWorld: line 208: ~/.config/bspwm/scripts/RandomWall: Permission denied
~/.config/bspwm/scripts/LaunchWorld: line 210: xsetroot: command not found
~/.config/bspwm/bspwmrc: line 34: nm-applet: command not found
[ 02/16/2023 20:25:56.690 parse_config_libconfig FATAL ERROR ] Failed to read configuration file "~/.config/bspwm/rices/emilia/picom.conf".
[ 02/16/2023 20:25:56.690 main FATAL ERROR ] Failed to create new session.
Couldn't spawn rule command.
```

**Comment by gh0stzk** [comment]
Of course as I said, a few days ago, I made the LaunchWorld file obsolete.

`~/.config/bspwm/scripts/LaunchWorld: line 32: ~/.config/termite/config: No such file or directory`

Somehow you are mixing old files with new ones. because LaunchWorld script doesnt exists anymore on my dotfiles.

remove ~/dotfiles and RiceInstaller from your home dir. i just updated the installer script, now deletes that dir if exist, then do this again.

`curl -O https://raw.githubusercontent.com/gh0stzk/dotfiles/master/RiceInstaller`
`chmod +x RiceInstaller`
`./RiceInstaller`

Or do it manually

`git clone --depth=1 https://github.com/gh0stzk/dotfiles.git`

And move files and dirs to respective dir.

**Comment by joelwoel** [comment]
Yeah. That was the issue. It had old dotfiles so git clone was ust skipping downloading them i think. I removed the old dotfiles, cloned the new ones and pasted them and it just started working on refresh. Thank you for your help. Really appreciate it
