### ISSUE TITLE
[BUG] Can't open firefox,thunar,etc in bspwm only

### ISSUE THREAD

**Issue by safe049** [gh0stzk/dotfiles#354]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

After a reboot,when i try to start firefox,it give me a inactive window and stuck my mouse and keyboard on it,the window is empty and transparent,i can move the mouse randomly and press win+q to get rid of it,quickly,i found that a lot of GUI software is starting to glitch,thunar have the same situation,when i switch into KDE PLASMA 6.2,firefox and other gui software work fine

### Reproducing the issue

open most GUIs like firefox,thunar,dolphin

### Expected behaviour

GUI apps could run normally on bspwm

### System information

Arch Linux x64
Installed since 2024/7/??
Installed KDE,GNOME,BSPWM,HYPRLAND,SWAY,QTILE
Using AMDGPU[Vega56]

**Comment by codeskin-r** [comment]
From personal experience, I can tell you that having all those window managers coexisting in the same system generally always causes issues. Right now, I’m using BSPWM with EndeavourOS and KDE, with a clean installation of the Ghostzk script, and everything is working great!


Good luckk

**Comment by gh0stzk** [comment]
Its hard to say, could be a lot of things, yes having a lot of DEs and Wms could affect but lets start with the beginning..
The problem starts after an update?
What login manager u use??
Using lightdm is useful because he creates a .xsession-errors.log file, will be nice if you share logs, to try to find out what is happening.

First edit the bspwmrc file, and comment the line that starts picom, start bspwm and see if your problem is fixed, if its fixed, picom just been updated so you need to play with your options, change backend glx to xrender, enable or disable vsync. You need to test.

Some time ago, there was a problem with the xdg-portal-* packages, that made apps opens with too much lag, and since you have a lot of des and wms, well maybe its thay way, but is the most unsure option.

Try to post logs pls, when you open apps on bspwm.

**Comment by safe049** [comment]
I'm currently using GDM,i will test everything out later,by the way,i look at the dmesg and journalctl and discovered nothing when opening apps on bspwm,i will try lightdm

**Comment by safe049** [comment]
tried to disable picom,nothing changed

**Comment by safe049** [comment]
solved by reinstalling dotfile and bspwm
