### ISSUE TITLE
Laptop brightness not working after running the script.

### ISSUE THREAD

**Issue by Juhayer-Al-Wasif** [gh0stzk/dotfiles#37]
Before running the script I can see battery icon and I can change the brightness through keyboard shortcuts(fn key). 
Bur after installing the rice, neither the battery icon is here but also I cannot change birghtness anyway.

**Comment by gh0stzk** [comment]
That's because I made my themes on a desktop pc and didn't add the module in polybar and hotkeys for brightness. But I already got a laptop and in the following days I will add that.

**Comment by gh0stzk** [comment]
> Before running the script I can see battery icon and I can change the brightness through keyboard shortcuts(fn key). Bur after installing the rice, neither the battery icon is here but also I cannot change birghtness anyway.

It is done, read changelog.

**Comment by Juhayer-Al-Wasif** [comment]
Brightness issue is fixed for laptops.
 
But some themes doesn't have the battery 🔋 icon.

**Comment by gh0stzk** [comment]
> Brightness issue is fixed for laptops.
> 
> But some themes doesn't have the battery battery icon.

Yes, i dont activate for all themes, the module is already available but not active, i cant test battery module "look" in all themes because i dont have time, but the module is there, if you wanna add it to a theme, just open "~/.config/bspwm/rices/RICENAME/" and there is a config.ini file, open and add  module wherever you want, for example in "isabel" looks loke this;
```
;Modules availables but not active: 
;	battery		brightness
modules-left = launcher sep2 bspwm sep2 weather
modules-center = title
modules-right = mpd_control sep2 updates sep filesystem sep cpu_bar sep memory_bar sep pulseaudio sep network sep date
```
i added in the file a note to let people know about the can add a battery and brightness module. Just add it in left, center or right modules.
