### ISSUE TITLE
[BUG] RiceEditor doesn't work

### ISSUE THREAD

**Issue by axlfranklin** [gh0stzk/dotfiles#371]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

I have this issue, followed every step for installation, I use AthennaOS btw, everything works fine but RiceEditor. Any doubt what can it be ? error:
Failed to execute: "Rice Editor"
Failed to execute the child process "RiceEditor"(file or directory doesn't exist) Any help ? :( 

### Reproducing the issue

I just simply tried to execute it.

### System information

Athena OS, Cybersecurity Focused Distro

**Comment by gh0stzk** [comment]
Yes in the past days i changed the structure of some files, https://github.com/gh0stzk/dotfiles/blob/master/CHANGELOG.md and deleted the rice editor app, because will not work anymore with recent changes, i guess you install the dots or update it in the past days?
i delete the app because i need to do a lot of changes and im improve it, i will try to push the new app at the end of week, im still finish the app.

![Shot-2024-12-03-125553](https://github.com/user-attachments/assets/32379303-8d4e-4cb4-9e0b-1aa6e3995c7f)

**Comment by axlfranklin** [comment]
Oh cool, your dotfiles are the best I ever seen so far, by the way, pretty excited for the new app version!

**Comment by CloseCoder** [comment]
I'm waiting for that too

**Comment by CloseCoder** [comment]
my laptop is low-end and i really like these dotfiles

**Comment by gh0stzk** [comment]
I just pushed the new app, just download it, put it on ~/.config/bspwm/src/ directory and give it execute permissions `chmod +x RiceEditor`

Be sure you updated my dots, the app works with latest commits, if you have theme-config.bash file inside all rices, you are fine.
