### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kavin-sorce** [gh0stzk/dotfiles#376]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

The ui is so slow so we cannot opearte in bspwn

### Reproducing the issue

Once the script has been installed it is not working from the begining

### System information

ARCH linux

**Comment by vmxt** [comment]
Hi @kavin-sorce, after reading your issues I cannot confirm which part are you referring to:

- Can you confirm if the slowness occurs immediately after installing the dotfiles script, or does it start happening after you make certain config? This will help us understand if the issue is with the initial setup or with a specific config.

- Can you be at least specific on the problem after installing the script on which part is not working? (have you been rebooted? are you in bspwm wm?)

**Comment by kavin-sorce** [comment]
hai i am on a VM this issue occurs once the script has been installed didn't change any configuration
