### ISSUE TITLE
Vs code or atom ?

### ISSUE THREAD

**Issue by harshalk612** [gh0stzk/dotfiles#66]
I want to change the theme of vs code and atom on the fly with matching rice. How should i approach it ??

**Comment by gh0stzk** [comment]
There is an app `sudo pacman -S xsettingsd` which changes gtk settings.

For a long time I have been thinking about adding it to my dotfiles but it would be adding gtk themes to the repository and that would make it very heavy for that reason I have not implemented it. But maybe one day.

Answering your question, install the application and here are several ways to do it:

One is adding a configuration file inside each rices folder and adding the command inside bspwmrc so that each time you change rice it takes the gtk configuration values ​​from the file you added inside each theme folder, would be something like

`xsettingsd --config=~/.config/bspwm/rices/"$RICETHEME"/xsettingsd &`

Another way would be adding a single configuration file, I would suggest inside ~/.config/bspwm/xsettingsd and inside each rices folder, edit the Theme.sh file and use the sed command to modify the gtk theme name each time you change rice, something similar to what I do inside Theme.sh to modify the values ​​of picom or alacritty.

Those would be two ways to do it, I hope I helped you to get on road on how to achieve it.

**Comment by harshalk612** [comment]
Thank you so much for answering, and can i get your terminal config which is like ( zombie ~ >> ) like this

**Comment by gh0stzk** [comment]
That terminal prompt is deprecated because nerd fonts in the last update deletes for some reason the big **>** and i had to replace it.

Answering your other question, ( _i will delete your other post, you can follow the conversation here_ ) 
The easy way to do it is creating an xsettingsd file inside all rices, that file must be look like this 

```
## Example configuration

Net/ThemeName "Arc-Dark"
Net/IconThemeName "Arc-Circle"
Gtk/CursorThemeName "Qogirr"
Net/EnableEventSounds "0"
Net/EnableInputFeedbackSounds "0"
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/Antialias 1
Xft/RGBA "none"

```
then in bspwmrc add a line like this `xsettingsd --config=~/.config/bspwm/rices/"$RICETHEME"/xsettingsd &`

That will load the config you just create for all rices everytime you change theme. Probably i will add that functionality in one month or two, if you wanna wait or try yourself if u dont wanna wait.

**Comment by harshalk612** [comment]
Okay this is for implementation of GTK theme and icon theme but for vs code and other editors like vim, atom, etc ?

**Comment by harshalk612** [comment]
See, i already figured out which vs code theme will be matching with each rice. I just want to make some script that will automatically apply that when changing rice ??

**Comment by gh0stzk** [comment]
> See, i already figured out which vs code theme will be matching with each rice. I just want to make some script that will automatically apply that when changing rice ??

ahh i follow you now. well i just use neovim and geany.
I don't know if vscode has a configuration file and in what location it is.

For each theme there is a Theme.sh file located at ~/.config/bspwm/rices/ricename/Theme.sh

In that file you could add a line with the sed command so that every time you change the theme that line is executed and modifies the configuration file of vscode.

But I don't use vscode, I don't know where it stores its configuration or the syntax that this file may have.

And it also depends a lot if the application that you want to change on the fly has that feature, for example, alacritty has it, when modifying its configuration file, the changes are automatically reflected, if the application does not have that feature, the only thing that what you can do is close it and open it if it was already open.

**Comment by harshalk612** [comment]
Okay i have already made a script in each rice folder using the vs code cli. How do I make it run every time I change my theme ??

It is like `change_theme.sh "Theme Name"`!!

**Comment by gh0stzk** [comment]
Seeing how your script works it occurs to me that you can move the script to ~/.config/bspwm/scripts/ _that folder is added to path if you use my dotfiles._

Then you can open the file Theme.sh inside **Aline** folder and add to the end of the file

`change_vscode_theme.sh MyThemeName1`

open Theme.sh inside **Emilia** rice and add

change_vscode_theme.sh My theme name 2

And do it in each Theme.sh file inside each rice. I think that would be the simplest way to implement it.

**Comment by harshalk612** [comment]
I understood clearly thank you.

**Comment by gh0stzk** [comment]
> I understood clearly thank you.
> 
> Edit: I want to Change the name of a theme how do i approach that ?? In what places there is the name of a theme ??

Some time ago i made changes to easily add or rename the rices, you only need to rename the rice directory.

**Comment by harshalk612** [comment]
So only the directory?? Everyone would be then changed accordingly ??

**Comment by gh0stzk** [comment]
Yes.
